package com.google.android.gms.internal.mlkit_common;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import com.zte.distbus.basetransfer.Status;

/* loaded from: classes.dex */
final class zzgp implements ObjectEncoder {
    private static final FieldDescriptor A;
    private static final FieldDescriptor A0;
    private static final FieldDescriptor B;
    private static final FieldDescriptor B0;
    private static final FieldDescriptor C;
    private static final FieldDescriptor C0;
    private static final FieldDescriptor D;
    private static final FieldDescriptor D0;
    private static final FieldDescriptor E;
    private static final FieldDescriptor E0;
    private static final FieldDescriptor F;
    private static final FieldDescriptor F0;
    private static final FieldDescriptor G;
    private static final FieldDescriptor G0;
    private static final FieldDescriptor H;
    private static final FieldDescriptor H0;
    private static final FieldDescriptor I;
    private static final FieldDescriptor I0;
    private static final FieldDescriptor J;
    private static final FieldDescriptor J0;
    private static final FieldDescriptor K;
    private static final FieldDescriptor K0;
    private static final FieldDescriptor L;
    private static final FieldDescriptor L0;
    private static final FieldDescriptor M;
    private static final FieldDescriptor M0;
    private static final FieldDescriptor N;
    private static final FieldDescriptor N0;
    private static final FieldDescriptor O;
    private static final FieldDescriptor O0;
    private static final FieldDescriptor P;
    private static final FieldDescriptor P0;
    private static final FieldDescriptor Q;
    private static final FieldDescriptor Q0;
    private static final FieldDescriptor R;
    private static final FieldDescriptor R0;
    private static final FieldDescriptor S;
    private static final FieldDescriptor S0;
    private static final FieldDescriptor T;
    private static final FieldDescriptor T0;
    private static final FieldDescriptor U;
    private static final FieldDescriptor U0;
    private static final FieldDescriptor V;
    private static final FieldDescriptor V0;
    private static final FieldDescriptor W;
    private static final FieldDescriptor W0;
    private static final FieldDescriptor X;
    private static final FieldDescriptor X0;
    private static final FieldDescriptor Y;
    private static final FieldDescriptor Y0;
    private static final FieldDescriptor Z;
    private static final FieldDescriptor Z0;

    /* renamed from: a, reason: collision with root package name */
    static final zzgp f11554a = new zzgp();
    private static final FieldDescriptor a0;
    private static final FieldDescriptor a1;

    /* renamed from: b, reason: collision with root package name */
    private static final FieldDescriptor f11555b;
    private static final FieldDescriptor b0;
    private static final FieldDescriptor b1;

    /* renamed from: c, reason: collision with root package name */
    private static final FieldDescriptor f11556c;
    private static final FieldDescriptor c0;
    private static final FieldDescriptor c1;

    /* renamed from: d, reason: collision with root package name */
    private static final FieldDescriptor f11557d;
    private static final FieldDescriptor d0;
    private static final FieldDescriptor d1;

    /* renamed from: e, reason: collision with root package name */
    private static final FieldDescriptor f11558e;
    private static final FieldDescriptor e0;
    private static final FieldDescriptor e1;

    /* renamed from: f, reason: collision with root package name */
    private static final FieldDescriptor f11559f;
    private static final FieldDescriptor f0;
    private static final FieldDescriptor f1;

    /* renamed from: g, reason: collision with root package name */
    private static final FieldDescriptor f11560g;
    private static final FieldDescriptor g0;
    private static final FieldDescriptor g1;

    /* renamed from: h, reason: collision with root package name */
    private static final FieldDescriptor f11561h;
    private static final FieldDescriptor h0;
    private static final FieldDescriptor h1;

    /* renamed from: i, reason: collision with root package name */
    private static final FieldDescriptor f11562i;
    private static final FieldDescriptor i0;
    private static final FieldDescriptor i1;

    /* renamed from: j, reason: collision with root package name */
    private static final FieldDescriptor f11563j;
    private static final FieldDescriptor j0;
    private static final FieldDescriptor j1;

    /* renamed from: k, reason: collision with root package name */
    private static final FieldDescriptor f11564k;
    private static final FieldDescriptor k0;
    private static final FieldDescriptor k1;

    /* renamed from: l, reason: collision with root package name */
    private static final FieldDescriptor f11565l;
    private static final FieldDescriptor l0;
    private static final FieldDescriptor l1;

    /* renamed from: m, reason: collision with root package name */
    private static final FieldDescriptor f11566m;
    private static final FieldDescriptor m0;
    private static final FieldDescriptor m1;

    /* renamed from: n, reason: collision with root package name */
    private static final FieldDescriptor f11567n;
    private static final FieldDescriptor n0;
    private static final FieldDescriptor n1;

    /* renamed from: o, reason: collision with root package name */
    private static final FieldDescriptor f11568o;
    private static final FieldDescriptor o0;
    private static final FieldDescriptor o1;

    /* renamed from: p, reason: collision with root package name */
    private static final FieldDescriptor f11569p;
    private static final FieldDescriptor p0;
    private static final FieldDescriptor p1;

    /* renamed from: q, reason: collision with root package name */
    private static final FieldDescriptor f11570q;
    private static final FieldDescriptor q0;
    private static final FieldDescriptor q1;

    /* renamed from: r, reason: collision with root package name */
    private static final FieldDescriptor f11571r;
    private static final FieldDescriptor r0;
    private static final FieldDescriptor r1;

    /* renamed from: s, reason: collision with root package name */
    private static final FieldDescriptor f11572s;
    private static final FieldDescriptor s0;
    private static final FieldDescriptor s1;
    private static final FieldDescriptor t;
    private static final FieldDescriptor t0;
    private static final FieldDescriptor t1;
    private static final FieldDescriptor u;
    private static final FieldDescriptor u0;
    private static final FieldDescriptor u1;
    private static final FieldDescriptor v;
    private static final FieldDescriptor v0;
    private static final FieldDescriptor v1;
    private static final FieldDescriptor w;
    private static final FieldDescriptor w0;
    private static final FieldDescriptor w1;
    private static final FieldDescriptor x;
    private static final FieldDescriptor x0;
    private static final FieldDescriptor x1;
    private static final FieldDescriptor y;
    private static final FieldDescriptor y0;
    private static final FieldDescriptor y1;
    private static final FieldDescriptor z;
    private static final FieldDescriptor z0;

    static {
        FieldDescriptor.Builder a2 = FieldDescriptor.a("systemInfo");
        zzay zzayVar = new zzay();
        zzayVar.a(1);
        f11555b = a2.b(zzayVar.b()).a();
        FieldDescriptor.Builder a3 = FieldDescriptor.a("eventName");
        zzay zzayVar2 = new zzay();
        zzayVar2.a(2);
        f11556c = a3.b(zzayVar2.b()).a();
        FieldDescriptor.Builder a4 = FieldDescriptor.a("isThickClient");
        zzay zzayVar3 = new zzay();
        zzayVar3.a(37);
        f11557d = a4.b(zzayVar3.b()).a();
        FieldDescriptor.Builder a5 = FieldDescriptor.a("clientType");
        zzay zzayVar4 = new zzay();
        zzayVar4.a(61);
        f11558e = a5.b(zzayVar4.b()).a();
        FieldDescriptor.Builder a6 = FieldDescriptor.a("modelDownloadLogEvent");
        zzay zzayVar5 = new zzay();
        zzayVar5.a(3);
        f11559f = a6.b(zzayVar5.b()).a();
        FieldDescriptor.Builder a7 = FieldDescriptor.a("customModelLoadLogEvent");
        zzay zzayVar6 = new zzay();
        zzayVar6.a(20);
        f11560g = a7.b(zzayVar6.b()).a();
        FieldDescriptor.Builder a8 = FieldDescriptor.a("customModelInferenceLogEvent");
        zzay zzayVar7 = new zzay();
        zzayVar7.a(4);
        f11561h = a8.b(zzayVar7.b()).a();
        FieldDescriptor.Builder a9 = FieldDescriptor.a("customModelCreateLogEvent");
        zzay zzayVar8 = new zzay();
        zzayVar8.a(29);
        f11562i = a9.b(zzayVar8.b()).a();
        FieldDescriptor.Builder a10 = FieldDescriptor.a("onDeviceFaceDetectionLogEvent");
        zzay zzayVar9 = new zzay();
        zzayVar9.a(5);
        f11563j = a10.b(zzayVar9.b()).a();
        FieldDescriptor.Builder a11 = FieldDescriptor.a("onDeviceFaceLoadLogEvent");
        zzay zzayVar10 = new zzay();
        zzayVar10.a(59);
        f11564k = a11.b(zzayVar10.b()).a();
        FieldDescriptor.Builder a12 = FieldDescriptor.a("onDeviceTextDetectionLogEvent");
        zzay zzayVar11 = new zzay();
        zzayVar11.a(6);
        f11565l = a12.b(zzayVar11.b()).a();
        FieldDescriptor.Builder a13 = FieldDescriptor.a("onDeviceTextDetectionLoadLogEvent");
        zzay zzayVar12 = new zzay();
        zzayVar12.a(79);
        f11566m = a13.b(zzayVar12.b()).a();
        FieldDescriptor.Builder a14 = FieldDescriptor.a("onDeviceBarcodeDetectionLogEvent");
        zzay zzayVar13 = new zzay();
        zzayVar13.a(7);
        f11567n = a14.b(zzayVar13.b()).a();
        FieldDescriptor.Builder a15 = FieldDescriptor.a("onDeviceBarcodeLoadLogEvent");
        zzay zzayVar14 = new zzay();
        zzayVar14.a(58);
        f11568o = a15.b(zzayVar14.b()).a();
        FieldDescriptor.Builder a16 = FieldDescriptor.a("onDeviceImageLabelCreateLogEvent");
        zzay zzayVar15 = new zzay();
        zzayVar15.a(48);
        f11569p = a16.b(zzayVar15.b()).a();
        FieldDescriptor.Builder a17 = FieldDescriptor.a("onDeviceImageLabelLoadLogEvent");
        zzay zzayVar16 = new zzay();
        zzayVar16.a(49);
        f11570q = a17.b(zzayVar16.b()).a();
        FieldDescriptor.Builder a18 = FieldDescriptor.a("onDeviceImageLabelDetectionLogEvent");
        zzay zzayVar17 = new zzay();
        zzayVar17.a(18);
        f11571r = a18.b(zzayVar17.b()).a();
        FieldDescriptor.Builder a19 = FieldDescriptor.a("onDeviceObjectCreateLogEvent");
        zzay zzayVar18 = new zzay();
        zzayVar18.a(26);
        f11572s = a19.b(zzayVar18.b()).a();
        FieldDescriptor.Builder a20 = FieldDescriptor.a("onDeviceObjectLoadLogEvent");
        zzay zzayVar19 = new zzay();
        zzayVar19.a(27);
        t = a20.b(zzayVar19.b()).a();
        FieldDescriptor.Builder a21 = FieldDescriptor.a("onDeviceObjectInferenceLogEvent");
        zzay zzayVar20 = new zzay();
        zzayVar20.a(28);
        u = a21.b(zzayVar20.b()).a();
        FieldDescriptor.Builder a22 = FieldDescriptor.a("onDevicePoseDetectionLogEvent");
        zzay zzayVar21 = new zzay();
        zzayVar21.a(44);
        v = a22.b(zzayVar21.b()).a();
        FieldDescriptor.Builder a23 = FieldDescriptor.a("onDeviceSegmentationLogEvent");
        zzay zzayVar22 = new zzay();
        zzayVar22.a(45);
        w = a23.b(zzayVar22.b()).a();
        FieldDescriptor.Builder a24 = FieldDescriptor.a("onDeviceSmartReplyLogEvent");
        zzay zzayVar23 = new zzay();
        zzayVar23.a(19);
        x = a24.b(zzayVar23.b()).a();
        FieldDescriptor.Builder a25 = FieldDescriptor.a("onDeviceLanguageIdentificationLogEvent");
        zzay zzayVar24 = new zzay();
        zzayVar24.a(21);
        y = a25.b(zzayVar24.b()).a();
        FieldDescriptor.Builder a26 = FieldDescriptor.a("onDeviceTranslationLogEvent");
        zzay zzayVar25 = new zzay();
        zzayVar25.a(22);
        z = a26.b(zzayVar25.b()).a();
        FieldDescriptor.Builder a27 = FieldDescriptor.a("cloudFaceDetectionLogEvent");
        zzay zzayVar26 = new zzay();
        zzayVar26.a(8);
        A = a27.b(zzayVar26.b()).a();
        FieldDescriptor.Builder a28 = FieldDescriptor.a("cloudCropHintDetectionLogEvent");
        zzay zzayVar27 = new zzay();
        zzayVar27.a(9);
        B = a28.b(zzayVar27.b()).a();
        FieldDescriptor.Builder a29 = FieldDescriptor.a("cloudDocumentTextDetectionLogEvent");
        zzay zzayVar28 = new zzay();
        zzayVar28.a(10);
        C = a29.b(zzayVar28.b()).a();
        FieldDescriptor.Builder a30 = FieldDescriptor.a("cloudImagePropertiesDetectionLogEvent");
        zzay zzayVar29 = new zzay();
        zzayVar29.a(11);
        D = a30.b(zzayVar29.b()).a();
        FieldDescriptor.Builder a31 = FieldDescriptor.a("cloudImageLabelDetectionLogEvent");
        zzay zzayVar30 = new zzay();
        zzayVar30.a(12);
        E = a31.b(zzayVar30.b()).a();
        FieldDescriptor.Builder a32 = FieldDescriptor.a("cloudLandmarkDetectionLogEvent");
        zzay zzayVar31 = new zzay();
        zzayVar31.a(13);
        F = a32.b(zzayVar31.b()).a();
        FieldDescriptor.Builder a33 = FieldDescriptor.a("cloudLogoDetectionLogEvent");
        zzay zzayVar32 = new zzay();
        zzayVar32.a(14);
        G = a33.b(zzayVar32.b()).a();
        FieldDescriptor.Builder a34 = FieldDescriptor.a("cloudSafeSearchDetectionLogEvent");
        zzay zzayVar33 = new zzay();
        zzayVar33.a(15);
        H = a34.b(zzayVar33.b()).a();
        FieldDescriptor.Builder a35 = FieldDescriptor.a("cloudTextDetectionLogEvent");
        zzay zzayVar34 = new zzay();
        zzayVar34.a(16);
        I = a35.b(zzayVar34.b()).a();
        FieldDescriptor.Builder a36 = FieldDescriptor.a("cloudWebSearchDetectionLogEvent");
        zzay zzayVar35 = new zzay();
        zzayVar35.a(17);
        J = a36.b(zzayVar35.b()).a();
        FieldDescriptor.Builder a37 = FieldDescriptor.a("automlImageLabelingCreateLogEvent");
        zzay zzayVar36 = new zzay();
        zzayVar36.a(23);
        K = a37.b(zzayVar36.b()).a();
        FieldDescriptor.Builder a38 = FieldDescriptor.a("automlImageLabelingLoadLogEvent");
        zzay zzayVar37 = new zzay();
        zzayVar37.a(24);
        L = a38.b(zzayVar37.b()).a();
        FieldDescriptor.Builder a39 = FieldDescriptor.a("automlImageLabelingInferenceLogEvent");
        zzay zzayVar38 = new zzay();
        zzayVar38.a(25);
        M = a39.b(zzayVar38.b()).a();
        FieldDescriptor.Builder a40 = FieldDescriptor.a("isModelDownloadedLogEvent");
        zzay zzayVar39 = new zzay();
        zzayVar39.a(39);
        N = a40.b(zzayVar39.b()).a();
        FieldDescriptor.Builder a41 = FieldDescriptor.a("deleteModelLogEvent");
        zzay zzayVar40 = new zzay();
        zzayVar40.a(40);
        O = a41.b(zzayVar40.b()).a();
        FieldDescriptor.Builder a42 = FieldDescriptor.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzay zzayVar41 = new zzay();
        zzayVar41.a(30);
        P = a42.b(zzayVar41.b()).a();
        FieldDescriptor.Builder a43 = FieldDescriptor.a("aggregatedCustomModelInferenceLogEvent");
        zzay zzayVar42 = new zzay();
        zzayVar42.a(31);
        Q = a43.b(zzayVar42.b()).a();
        FieldDescriptor.Builder a44 = FieldDescriptor.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzay zzayVar43 = new zzay();
        zzayVar43.a(32);
        R = a44.b(zzayVar43.b()).a();
        FieldDescriptor.Builder a45 = FieldDescriptor.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzay zzayVar44 = new zzay();
        zzayVar44.a(33);
        S = a45.b(zzayVar44.b()).a();
        FieldDescriptor.Builder a46 = FieldDescriptor.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzay zzayVar45 = new zzay();
        zzayVar45.a(34);
        T = a46.b(zzayVar45.b()).a();
        FieldDescriptor.Builder a47 = FieldDescriptor.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzay zzayVar46 = new zzay();
        zzayVar46.a(35);
        U = a47.b(zzayVar46.b()).a();
        FieldDescriptor.Builder a48 = FieldDescriptor.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzay zzayVar47 = new zzay();
        zzayVar47.a(36);
        V = a48.b(zzayVar47.b()).a();
        FieldDescriptor.Builder a49 = FieldDescriptor.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzay zzayVar48 = new zzay();
        zzayVar48.a(46);
        W = a49.b(zzayVar48.b()).a();
        FieldDescriptor.Builder a50 = FieldDescriptor.a("aggregatedOnDeviceSegmentationLogEvent");
        zzay zzayVar49 = new zzay();
        zzayVar49.a(47);
        X = a50.b(zzayVar49.b()).a();
        FieldDescriptor.Builder a51 = FieldDescriptor.a("pipelineAccelerationInferenceEvents");
        zzay zzayVar50 = new zzay();
        zzayVar50.a(69);
        Y = a51.b(zzayVar50.b()).a();
        FieldDescriptor.Builder a52 = FieldDescriptor.a("remoteConfigLogEvent");
        zzay zzayVar51 = new zzay();
        zzayVar51.a(42);
        Z = a52.b(zzayVar51.b()).a();
        FieldDescriptor.Builder a53 = FieldDescriptor.a("inputImageConstructionLogEvent");
        zzay zzayVar52 = new zzay();
        zzayVar52.a(50);
        a0 = a53.b(zzayVar52.b()).a();
        FieldDescriptor.Builder a54 = FieldDescriptor.a("leakedHandleEvent");
        zzay zzayVar53 = new zzay();
        zzayVar53.a(51);
        b0 = a54.b(zzayVar53.b()).a();
        FieldDescriptor.Builder a55 = FieldDescriptor.a("cameraSourceLogEvent");
        zzay zzayVar54 = new zzay();
        zzayVar54.a(52);
        c0 = a55.b(zzayVar54.b()).a();
        FieldDescriptor.Builder a56 = FieldDescriptor.a("imageLabelOptionalModuleLogEvent");
        zzay zzayVar55 = new zzay();
        zzayVar55.a(53);
        d0 = a56.b(zzayVar55.b()).a();
        FieldDescriptor.Builder a57 = FieldDescriptor.a("languageIdentificationOptionalModuleLogEvent");
        zzay zzayVar56 = new zzay();
        zzayVar56.a(54);
        e0 = a57.b(zzayVar56.b()).a();
        FieldDescriptor.Builder a58 = FieldDescriptor.a("faceDetectionOptionalModuleLogEvent");
        zzay zzayVar57 = new zzay();
        zzayVar57.a(60);
        f0 = a58.b(zzayVar57.b()).a();
        FieldDescriptor.Builder a59 = FieldDescriptor.a("documentDetectionOptionalModuleLogEvent");
        zzay zzayVar58 = new zzay();
        zzayVar58.a(85);
        g0 = a59.b(zzayVar58.b()).a();
        FieldDescriptor.Builder a60 = FieldDescriptor.a("documentCroppingOptionalModuleLogEvent");
        zzay zzayVar59 = new zzay();
        zzayVar59.a(86);
        h0 = a60.b(zzayVar59.b()).a();
        FieldDescriptor.Builder a61 = FieldDescriptor.a("documentEnhancementOptionalModuleLogEvent");
        zzay zzayVar60 = new zzay();
        zzayVar60.a(87);
        i0 = a61.b(zzayVar60.b()).a();
        FieldDescriptor.Builder a62 = FieldDescriptor.a("nlClassifierOptionalModuleLogEvent");
        zzay zzayVar61 = new zzay();
        zzayVar61.a(55);
        j0 = a62.b(zzayVar61.b()).a();
        FieldDescriptor.Builder a63 = FieldDescriptor.a("nlClassifierClientLibraryLogEvent");
        zzay zzayVar62 = new zzay();
        zzayVar62.a(56);
        k0 = a63.b(zzayVar62.b()).a();
        FieldDescriptor.Builder a64 = FieldDescriptor.a("accelerationAllowlistLogEvent");
        zzay zzayVar63 = new zzay();
        zzayVar63.a(57);
        l0 = a64.b(zzayVar63.b()).a();
        FieldDescriptor.Builder a65 = FieldDescriptor.a("toxicityDetectionCreateEvent");
        zzay zzayVar64 = new zzay();
        zzayVar64.a(62);
        m0 = a65.b(zzayVar64.b()).a();
        FieldDescriptor.Builder a66 = FieldDescriptor.a("toxicityDetectionLoadEvent");
        zzay zzayVar65 = new zzay();
        zzayVar65.a(63);
        n0 = a66.b(zzayVar65.b()).a();
        FieldDescriptor.Builder a67 = FieldDescriptor.a("toxicityDetectionInferenceEvent");
        zzay zzayVar66 = new zzay();
        zzayVar66.a(64);
        o0 = a67.b(zzayVar66.b()).a();
        FieldDescriptor.Builder a68 = FieldDescriptor.a("barcodeDetectionOptionalModuleLogEvent");
        zzay zzayVar67 = new zzay();
        zzayVar67.a(65);
        p0 = a68.b(zzayVar67.b()).a();
        FieldDescriptor.Builder a69 = FieldDescriptor.a("customImageLabelOptionalModuleLogEvent");
        zzay zzayVar68 = new zzay();
        zzayVar68.a(66);
        q0 = a69.b(zzayVar68.b()).a();
        FieldDescriptor.Builder a70 = FieldDescriptor.a("codeScannerScanApiEvent");
        zzay zzayVar69 = new zzay();
        zzayVar69.a(67);
        r0 = a70.b(zzayVar69.b()).a();
        FieldDescriptor.Builder a71 = FieldDescriptor.a("codeScannerOptionalModuleEvent");
        zzay zzayVar70 = new zzay();
        zzayVar70.a(68);
        s0 = a71.b(zzayVar70.b()).a();
        FieldDescriptor.Builder a72 = FieldDescriptor.a("onDeviceExplicitContentCreateLogEvent");
        zzay zzayVar71 = new zzay();
        zzayVar71.a(70);
        t0 = a72.b(zzayVar71.b()).a();
        FieldDescriptor.Builder a73 = FieldDescriptor.a("onDeviceExplicitContentLoadLogEvent");
        zzay zzayVar72 = new zzay();
        zzayVar72.a(71);
        u0 = a73.b(zzayVar72.b()).a();
        FieldDescriptor.Builder a74 = FieldDescriptor.a("onDeviceExplicitContentInferenceLogEvent");
        zzay zzayVar73 = new zzay();
        zzayVar73.a(72);
        v0 = a74.b(zzayVar73.b()).a();
        FieldDescriptor.Builder a75 = FieldDescriptor.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzay zzayVar74 = new zzay();
        zzayVar74.a(73);
        w0 = a75.b(zzayVar74.b()).a();
        FieldDescriptor.Builder a76 = FieldDescriptor.a("onDeviceFaceMeshCreateLogEvent");
        zzay zzayVar75 = new zzay();
        zzayVar75.a(74);
        x0 = a76.b(zzayVar75.b()).a();
        FieldDescriptor.Builder a77 = FieldDescriptor.a("onDeviceFaceMeshLoadLogEvent");
        zzay zzayVar76 = new zzay();
        zzayVar76.a(75);
        y0 = a77.b(zzayVar76.b()).a();
        FieldDescriptor.Builder a78 = FieldDescriptor.a("onDeviceFaceMeshLogEvent");
        zzay zzayVar77 = new zzay();
        zzayVar77.a(76);
        z0 = a78.b(zzayVar77.b()).a();
        FieldDescriptor.Builder a79 = FieldDescriptor.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzay zzayVar78 = new zzay();
        zzayVar78.a(77);
        A0 = a79.b(zzayVar78.b()).a();
        FieldDescriptor.Builder a80 = FieldDescriptor.a("smartReplyOptionalModuleLogEvent");
        zzay zzayVar79 = new zzay();
        zzayVar79.a(78);
        B0 = a80.b(zzayVar79.b()).a();
        FieldDescriptor.Builder a81 = FieldDescriptor.a("textDetectionOptionalModuleLogEvent");
        zzay zzayVar80 = new zzay();
        zzayVar80.a(80);
        C0 = a81.b(zzayVar80.b()).a();
        FieldDescriptor.Builder a82 = FieldDescriptor.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzay zzayVar81 = new zzay();
        zzayVar81.a(81);
        D0 = a82.b(zzayVar81.b()).a();
        FieldDescriptor.Builder a83 = FieldDescriptor.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzay zzayVar82 = new zzay();
        zzayVar82.a(82);
        E0 = a83.b(zzayVar82.b()).a();
        FieldDescriptor.Builder a84 = FieldDescriptor.a("onDeviceImageQualityAnalysisLogEvent");
        zzay zzayVar83 = new zzay();
        zzayVar83.a(83);
        F0 = a84.b(zzayVar83.b()).a();
        FieldDescriptor.Builder a85 = FieldDescriptor.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzay zzayVar84 = new zzay();
        zzayVar84.a(84);
        G0 = a85.b(zzayVar84.b()).a();
        FieldDescriptor.Builder a86 = FieldDescriptor.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzay zzayVar85 = new zzay();
        zzayVar85.a(88);
        H0 = a86.b(zzayVar85.b()).a();
        FieldDescriptor.Builder a87 = FieldDescriptor.a("imageCaptioningOptionalModuleLogEvent");
        zzay zzayVar86 = new zzay();
        zzayVar86.a(89);
        I0 = a87.b(zzayVar86.b()).a();
        FieldDescriptor.Builder a88 = FieldDescriptor.a("onDeviceImageCaptioningCreateLogEvent");
        zzay zzayVar87 = new zzay();
        zzayVar87.a(90);
        J0 = a88.b(zzayVar87.b()).a();
        FieldDescriptor.Builder a89 = FieldDescriptor.a("onDeviceImageCaptioningLoadLogEvent");
        zzay zzayVar88 = new zzay();
        zzayVar88.a(91);
        K0 = a89.b(zzayVar88.b()).a();
        FieldDescriptor.Builder a90 = FieldDescriptor.a("onDeviceImageCaptioningInferenceLogEvent");
        zzay zzayVar89 = new zzay();
        zzayVar89.a(92);
        L0 = a90.b(zzayVar89.b()).a();
        FieldDescriptor.Builder a91 = FieldDescriptor.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzay zzayVar90 = new zzay();
        zzayVar90.a(93);
        M0 = a91.b(zzayVar90.b()).a();
        FieldDescriptor.Builder a92 = FieldDescriptor.a("onDeviceDocumentDetectionCreateLogEvent");
        zzay zzayVar91 = new zzay();
        zzayVar91.a(94);
        N0 = a92.b(zzayVar91.b()).a();
        FieldDescriptor.Builder a93 = FieldDescriptor.a("onDeviceDocumentDetectionLoadLogEvent");
        zzay zzayVar92 = new zzay();
        zzayVar92.a(95);
        O0 = a93.b(zzayVar92.b()).a();
        FieldDescriptor.Builder a94 = FieldDescriptor.a("onDeviceDocumentDetectionLogEvent");
        zzay zzayVar93 = new zzay();
        zzayVar93.a(96);
        P0 = a94.b(zzayVar93.b()).a();
        FieldDescriptor.Builder a95 = FieldDescriptor.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzay zzayVar94 = new zzay();
        zzayVar94.a(97);
        Q0 = a95.b(zzayVar94.b()).a();
        FieldDescriptor.Builder a96 = FieldDescriptor.a("onDeviceDocumentCroppingCreateLogEvent");
        zzay zzayVar95 = new zzay();
        zzayVar95.a(98);
        R0 = a96.b(zzayVar95.b()).a();
        FieldDescriptor.Builder a97 = FieldDescriptor.a("onDeviceDocumentCroppingLoadLogEvent");
        zzay zzayVar96 = new zzay();
        zzayVar96.a(99);
        S0 = a97.b(zzayVar96.b()).a();
        FieldDescriptor.Builder a98 = FieldDescriptor.a("onDeviceDocumentCroppingLogEvent");
        zzay zzayVar97 = new zzay();
        zzayVar97.a(100);
        T0 = a98.b(zzayVar97.b()).a();
        FieldDescriptor.Builder a99 = FieldDescriptor.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzay zzayVar98 = new zzay();
        zzayVar98.a(101);
        U0 = a99.b(zzayVar98.b()).a();
        FieldDescriptor.Builder a100 = FieldDescriptor.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzay zzayVar99 = new zzay();
        zzayVar99.a(102);
        V0 = a100.b(zzayVar99.b()).a();
        FieldDescriptor.Builder a101 = FieldDescriptor.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzay zzayVar100 = new zzay();
        zzayVar100.a(Status.BLE_DISCONNECTING);
        W0 = a101.b(zzayVar100.b()).a();
        FieldDescriptor.Builder a102 = FieldDescriptor.a("onDeviceDocumentEnhancementLogEvent");
        zzay zzayVar101 = new zzay();
        zzayVar101.a(Status.BLE_ERROR);
        X0 = a102.b(zzayVar101.b()).a();
        FieldDescriptor.Builder a103 = FieldDescriptor.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzay zzayVar102 = new zzay();
        zzayVar102.a(105);
        Y0 = a103.b(zzayVar102.b()).a();
        FieldDescriptor.Builder a104 = FieldDescriptor.a("scannerAutoZoomEvent");
        zzay zzayVar103 = new zzay();
        zzayVar103.a(106);
        Z0 = a104.b(zzayVar103.b()).a();
        FieldDescriptor.Builder a105 = FieldDescriptor.a("lowLightAutoExposureComputationEvent");
        zzay zzayVar104 = new zzay();
        zzayVar104.a(107);
        a1 = a105.b(zzayVar104.b()).a();
        FieldDescriptor.Builder a106 = FieldDescriptor.a("lowLightFrameProcessEvent");
        zzay zzayVar105 = new zzay();
        zzayVar105.a(108);
        b1 = a106.b(zzayVar105.b()).a();
        FieldDescriptor.Builder a107 = FieldDescriptor.a("lowLightSceneDetectionEvent");
        zzay zzayVar106 = new zzay();
        zzayVar106.a(109);
        c1 = a107.b(zzayVar106.b()).a();
        FieldDescriptor.Builder a108 = FieldDescriptor.a("onDeviceStainRemovalLogEvent");
        zzay zzayVar107 = new zzay();
        zzayVar107.a(110);
        d1 = a108.b(zzayVar107.b()).a();
        FieldDescriptor.Builder a109 = FieldDescriptor.a("aggregatedOnDeviceStainRemovalLogEvent");
        zzay zzayVar108 = new zzay();
        zzayVar108.a(111);
        e1 = a109.b(zzayVar108.b()).a();
        FieldDescriptor.Builder a110 = FieldDescriptor.a("stainRemovalOptionalModuleLogEvent");
        zzay zzayVar109 = new zzay();
        zzayVar109.a(112);
        f1 = a110.b(zzayVar109.b()).a();
        FieldDescriptor.Builder a111 = FieldDescriptor.a("onDeviceShadowRemovalLogEvent");
        zzay zzayVar110 = new zzay();
        zzayVar110.a(113);
        g1 = a111.b(zzayVar110.b()).a();
        FieldDescriptor.Builder a112 = FieldDescriptor.a("aggregatedOnDeviceShadowRemovalLogEvent");
        zzay zzayVar111 = new zzay();
        zzayVar111.a(114);
        h1 = a112.b(zzayVar111.b()).a();
        FieldDescriptor.Builder a113 = FieldDescriptor.a("shadowRemovalOptionalModuleLogEvent");
        zzay zzayVar112 = new zzay();
        zzayVar112.a(115);
        i1 = a113.b(zzayVar112.b()).a();
        FieldDescriptor.Builder a114 = FieldDescriptor.a("onDeviceDigitalInkSegmentationLogEvent");
        zzay zzayVar113 = new zzay();
        zzayVar113.a(116);
        j1 = a114.b(zzayVar113.b()).a();
        FieldDescriptor.Builder a115 = FieldDescriptor.a("onDeviceDocumentScannerStartLogEvent");
        zzay zzayVar114 = new zzay();
        zzayVar114.a(117);
        k1 = a115.b(zzayVar114.b()).a();
        FieldDescriptor.Builder a116 = FieldDescriptor.a("onDeviceDocumentScannerFinishLogEvent");
        zzay zzayVar115 = new zzay();
        zzayVar115.a(118);
        l1 = a116.b(zzayVar115.b()).a();
        FieldDescriptor.Builder a117 = FieldDescriptor.a("onDeviceDocumentScannerUiStartLogEvent");
        zzay zzayVar116 = new zzay();
        zzayVar116.a(119);
        m1 = a117.b(zzayVar116.b()).a();
        FieldDescriptor.Builder a118 = FieldDescriptor.a("onDeviceDocumentScannerUiFinishLogEvent");
        zzay zzayVar117 = new zzay();
        zzayVar117.a(120);
        n1 = a118.b(zzayVar117.b()).a();
        FieldDescriptor.Builder a119 = FieldDescriptor.a("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzay zzayVar118 = new zzay();
        zzayVar118.a(121);
        o1 = a119.b(zzayVar118.b()).a();
        FieldDescriptor.Builder a120 = FieldDescriptor.a("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzay zzayVar119 = new zzay();
        zzayVar119.a(122);
        p1 = a120.b(zzayVar119.b()).a();
        FieldDescriptor.Builder a121 = FieldDescriptor.a("onDeviceDocumentScannerUiCreateLogEvent");
        zzay zzayVar120 = new zzay();
        zzayVar120.a(123);
        q1 = a121.b(zzayVar120.b()).a();
        FieldDescriptor.Builder a122 = FieldDescriptor.a("onDeviceSubjectSegmentationCreateLogEvent");
        zzay zzayVar121 = new zzay();
        zzayVar121.a(124);
        r1 = a122.b(zzayVar121.b()).a();
        FieldDescriptor.Builder a123 = FieldDescriptor.a("onDeviceSubjectSegmentationLoadLogEvent");
        zzay zzayVar122 = new zzay();
        zzayVar122.a(125);
        s1 = a123.b(zzayVar122.b()).a();
        FieldDescriptor.Builder a124 = FieldDescriptor.a("onDeviceSubjectSegmentationInferenceLogEvent");
        zzay zzayVar123 = new zzay();
        zzayVar123.a(126);
        t1 = a124.b(zzayVar123.b()).a();
        FieldDescriptor.Builder a125 = FieldDescriptor.a("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzay zzayVar124 = new zzay();
        zzayVar124.a(127);
        u1 = a125.b(zzayVar124.b()).a();
        FieldDescriptor.Builder a126 = FieldDescriptor.a("subjectSegmentationOptionalModuleLogEvent");
        zzay zzayVar125 = new zzay();
        zzayVar125.a(128);
        v1 = a126.b(zzayVar125.b()).a();
        FieldDescriptor.Builder a127 = FieldDescriptor.a("documentScannerUiModuleScreenViewEvent");
        zzay zzayVar126 = new zzay();
        zzayVar126.a(129);
        w1 = a127.b(zzayVar126.b()).a();
        FieldDescriptor.Builder a128 = FieldDescriptor.a("documentScannerUiModuleScreenClickEvent");
        zzay zzayVar127 = new zzay();
        zzayVar127.a(130);
        x1 = a128.b(zzayVar127.b()).a();
        FieldDescriptor.Builder a129 = FieldDescriptor.a("documentScannerUiModuleScreenErrorEvent");
        zzay zzayVar128 = new zzay();
        zzayVar128.a(131);
        y1 = a129.b(zzayVar128.b()).a();
    }

    private zzgp() {
    }

    @Override // com.google.firebase.encoders.ObjectEncoder
    public final /* bridge */ /* synthetic */ void a(Object obj, Object obj2) {
        zzmy zzmyVar = (zzmy) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.c(f11555b, zzmyVar.f());
        objectEncoderContext.c(f11556c, zzmyVar.d());
        objectEncoderContext.c(f11557d, null);
        objectEncoderContext.c(f11558e, null);
        objectEncoderContext.c(f11559f, zzmyVar.e());
        objectEncoderContext.c(f11560g, null);
        objectEncoderContext.c(f11561h, null);
        objectEncoderContext.c(f11562i, null);
        objectEncoderContext.c(f11563j, null);
        objectEncoderContext.c(f11564k, null);
        objectEncoderContext.c(f11565l, null);
        objectEncoderContext.c(f11566m, null);
        objectEncoderContext.c(f11567n, null);
        objectEncoderContext.c(f11568o, null);
        objectEncoderContext.c(f11569p, null);
        objectEncoderContext.c(f11570q, null);
        objectEncoderContext.c(f11571r, null);
        objectEncoderContext.c(f11572s, null);
        objectEncoderContext.c(t, null);
        objectEncoderContext.c(u, null);
        objectEncoderContext.c(v, null);
        objectEncoderContext.c(w, null);
        objectEncoderContext.c(x, null);
        objectEncoderContext.c(y, null);
        objectEncoderContext.c(z, null);
        objectEncoderContext.c(A, null);
        objectEncoderContext.c(B, null);
        objectEncoderContext.c(C, null);
        objectEncoderContext.c(D, null);
        objectEncoderContext.c(E, null);
        objectEncoderContext.c(F, null);
        objectEncoderContext.c(G, null);
        objectEncoderContext.c(H, null);
        objectEncoderContext.c(I, null);
        objectEncoderContext.c(J, null);
        objectEncoderContext.c(K, null);
        objectEncoderContext.c(L, null);
        objectEncoderContext.c(M, null);
        objectEncoderContext.c(N, zzmyVar.b());
        objectEncoderContext.c(O, zzmyVar.a());
        objectEncoderContext.c(P, null);
        objectEncoderContext.c(Q, null);
        objectEncoderContext.c(R, null);
        objectEncoderContext.c(S, null);
        objectEncoderContext.c(T, null);
        objectEncoderContext.c(U, null);
        objectEncoderContext.c(V, null);
        objectEncoderContext.c(W, null);
        objectEncoderContext.c(X, null);
        objectEncoderContext.c(Y, null);
        objectEncoderContext.c(Z, null);
        objectEncoderContext.c(a0, null);
        objectEncoderContext.c(b0, zzmyVar.c());
        objectEncoderContext.c(c0, null);
        objectEncoderContext.c(d0, null);
        objectEncoderContext.c(e0, null);
        objectEncoderContext.c(f0, null);
        objectEncoderContext.c(g0, null);
        objectEncoderContext.c(h0, null);
        objectEncoderContext.c(i0, null);
        objectEncoderContext.c(j0, null);
        objectEncoderContext.c(k0, null);
        objectEncoderContext.c(l0, null);
        objectEncoderContext.c(m0, null);
        objectEncoderContext.c(n0, null);
        objectEncoderContext.c(o0, null);
        objectEncoderContext.c(p0, null);
        objectEncoderContext.c(q0, null);
        objectEncoderContext.c(r0, null);
        objectEncoderContext.c(s0, null);
        objectEncoderContext.c(t0, null);
        objectEncoderContext.c(u0, null);
        objectEncoderContext.c(v0, null);
        objectEncoderContext.c(w0, null);
        objectEncoderContext.c(x0, null);
        objectEncoderContext.c(y0, null);
        objectEncoderContext.c(z0, null);
        objectEncoderContext.c(A0, null);
        objectEncoderContext.c(B0, null);
        objectEncoderContext.c(C0, null);
        objectEncoderContext.c(D0, null);
        objectEncoderContext.c(E0, null);
        objectEncoderContext.c(F0, null);
        objectEncoderContext.c(G0, null);
        objectEncoderContext.c(H0, null);
        objectEncoderContext.c(I0, null);
        objectEncoderContext.c(J0, null);
        objectEncoderContext.c(K0, null);
        objectEncoderContext.c(L0, null);
        objectEncoderContext.c(M0, null);
        objectEncoderContext.c(N0, null);
        objectEncoderContext.c(O0, null);
        objectEncoderContext.c(P0, null);
        objectEncoderContext.c(Q0, null);
        objectEncoderContext.c(R0, null);
        objectEncoderContext.c(S0, null);
        objectEncoderContext.c(T0, null);
        objectEncoderContext.c(U0, null);
        objectEncoderContext.c(V0, null);
        objectEncoderContext.c(W0, null);
        objectEncoderContext.c(X0, null);
        objectEncoderContext.c(Y0, null);
        objectEncoderContext.c(Z0, null);
        objectEncoderContext.c(a1, null);
        objectEncoderContext.c(b1, null);
        objectEncoderContext.c(c1, null);
        objectEncoderContext.c(d1, null);
        objectEncoderContext.c(e1, null);
        objectEncoderContext.c(f1, null);
        objectEncoderContext.c(g1, null);
        objectEncoderContext.c(h1, null);
        objectEncoderContext.c(i1, null);
        objectEncoderContext.c(j1, null);
        objectEncoderContext.c(k1, null);
        objectEncoderContext.c(l1, null);
        objectEncoderContext.c(m1, null);
        objectEncoderContext.c(n1, null);
        objectEncoderContext.c(o1, null);
        objectEncoderContext.c(p1, null);
        objectEncoderContext.c(q1, null);
        objectEncoderContext.c(r1, null);
        objectEncoderContext.c(s1, null);
        objectEncoderContext.c(t1, null);
        objectEncoderContext.c(u1, null);
        objectEncoderContext.c(v1, null);
        objectEncoderContext.c(w1, null);
        objectEncoderContext.c(x1, null);
        objectEncoderContext.c(y1, null);
    }
}
