package com.google.android.gms.internal.mlkit_vision_common;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;

/* loaded from: classes.dex */
final class zzeo implements ObjectEncoder {
    private static final FieldDescriptor A;
    private static final FieldDescriptor A0;
    private static final FieldDescriptor B;
    private static final FieldDescriptor B0;
    private static final FieldDescriptor C;
    private static final FieldDescriptor C0;
    private static final FieldDescriptor D;
    private static final FieldDescriptor D0;
    private static final FieldDescriptor E;
    private static final FieldDescriptor E0;
    private static final FieldDescriptor F;
    private static final FieldDescriptor F0;
    private static final FieldDescriptor G;
    private static final FieldDescriptor G0;
    private static final FieldDescriptor H;
    private static final FieldDescriptor H0;
    private static final FieldDescriptor I;
    private static final FieldDescriptor I0;
    private static final FieldDescriptor J;
    private static final FieldDescriptor J0;
    private static final FieldDescriptor K;
    private static final FieldDescriptor K0;
    private static final FieldDescriptor L;
    private static final FieldDescriptor L0;
    private static final FieldDescriptor M;
    private static final FieldDescriptor M0;
    private static final FieldDescriptor N;
    private static final FieldDescriptor O;
    private static final FieldDescriptor P;
    private static final FieldDescriptor Q;
    private static final FieldDescriptor R;
    private static final FieldDescriptor S;
    private static final FieldDescriptor T;
    private static final FieldDescriptor U;
    private static final FieldDescriptor V;
    private static final FieldDescriptor W;
    private static final FieldDescriptor X;
    private static final FieldDescriptor Y;
    private static final FieldDescriptor Z;

    /* renamed from: a, reason: collision with root package name */
    static final zzeo f12229a = new zzeo();
    private static final FieldDescriptor a0;

    /* renamed from: b, reason: collision with root package name */
    private static final FieldDescriptor f12230b;
    private static final FieldDescriptor b0;

    /* renamed from: c, reason: collision with root package name */
    private static final FieldDescriptor f12231c;
    private static final FieldDescriptor c0;

    /* renamed from: d, reason: collision with root package name */
    private static final FieldDescriptor f12232d;
    private static final FieldDescriptor d0;

    /* renamed from: e, reason: collision with root package name */
    private static final FieldDescriptor f12233e;
    private static final FieldDescriptor e0;

    /* renamed from: f, reason: collision with root package name */
    private static final FieldDescriptor f12234f;
    private static final FieldDescriptor f0;

    /* renamed from: g, reason: collision with root package name */
    private static final FieldDescriptor f12235g;
    private static final FieldDescriptor g0;

    /* renamed from: h, reason: collision with root package name */
    private static final FieldDescriptor f12236h;
    private static final FieldDescriptor h0;

    /* renamed from: i, reason: collision with root package name */
    private static final FieldDescriptor f12237i;
    private static final FieldDescriptor i0;

    /* renamed from: j, reason: collision with root package name */
    private static final FieldDescriptor f12238j;
    private static final FieldDescriptor j0;

    /* renamed from: k, reason: collision with root package name */
    private static final FieldDescriptor f12239k;
    private static final FieldDescriptor k0;

    /* renamed from: l, reason: collision with root package name */
    private static final FieldDescriptor f12240l;
    private static final FieldDescriptor l0;

    /* renamed from: m, reason: collision with root package name */
    private static final FieldDescriptor f12241m;
    private static final FieldDescriptor m0;

    /* renamed from: n, reason: collision with root package name */
    private static final FieldDescriptor f12242n;
    private static final FieldDescriptor n0;

    /* renamed from: o, reason: collision with root package name */
    private static final FieldDescriptor f12243o;
    private static final FieldDescriptor o0;

    /* renamed from: p, reason: collision with root package name */
    private static final FieldDescriptor f12244p;
    private static final FieldDescriptor p0;

    /* renamed from: q, reason: collision with root package name */
    private static final FieldDescriptor f12245q;
    private static final FieldDescriptor q0;

    /* renamed from: r, reason: collision with root package name */
    private static final FieldDescriptor f12246r;
    private static final FieldDescriptor r0;

    /* renamed from: s, reason: collision with root package name */
    private static final FieldDescriptor f12247s;
    private static final FieldDescriptor s0;
    private static final FieldDescriptor t;
    private static final FieldDescriptor t0;
    private static final FieldDescriptor u;
    private static final FieldDescriptor u0;
    private static final FieldDescriptor v;
    private static final FieldDescriptor v0;
    private static final FieldDescriptor w;
    private static final FieldDescriptor w0;
    private static final FieldDescriptor x;
    private static final FieldDescriptor x0;
    private static final FieldDescriptor y;
    private static final FieldDescriptor y0;
    private static final FieldDescriptor z;
    private static final FieldDescriptor z0;

    static {
        FieldDescriptor.Builder a2 = FieldDescriptor.a("systemInfo");
        zzae zzaeVar = new zzae();
        zzaeVar.a(1);
        f12230b = a2.b(zzaeVar.b()).a();
        FieldDescriptor.Builder a3 = FieldDescriptor.a("eventName");
        zzae zzaeVar2 = new zzae();
        zzaeVar2.a(2);
        f12231c = a3.b(zzaeVar2.b()).a();
        FieldDescriptor.Builder a4 = FieldDescriptor.a("isThickClient");
        zzae zzaeVar3 = new zzae();
        zzaeVar3.a(37);
        f12232d = a4.b(zzaeVar3.b()).a();
        FieldDescriptor.Builder a5 = FieldDescriptor.a("clientType");
        zzae zzaeVar4 = new zzae();
        zzaeVar4.a(61);
        f12233e = a5.b(zzaeVar4.b()).a();
        FieldDescriptor.Builder a6 = FieldDescriptor.a("modelDownloadLogEvent");
        zzae zzaeVar5 = new zzae();
        zzaeVar5.a(3);
        f12234f = a6.b(zzaeVar5.b()).a();
        FieldDescriptor.Builder a7 = FieldDescriptor.a("customModelLoadLogEvent");
        zzae zzaeVar6 = new zzae();
        zzaeVar6.a(20);
        f12235g = a7.b(zzaeVar6.b()).a();
        FieldDescriptor.Builder a8 = FieldDescriptor.a("customModelInferenceLogEvent");
        zzae zzaeVar7 = new zzae();
        zzaeVar7.a(4);
        f12236h = a8.b(zzaeVar7.b()).a();
        FieldDescriptor.Builder a9 = FieldDescriptor.a("customModelCreateLogEvent");
        zzae zzaeVar8 = new zzae();
        zzaeVar8.a(29);
        f12237i = a9.b(zzaeVar8.b()).a();
        FieldDescriptor.Builder a10 = FieldDescriptor.a("onDeviceFaceDetectionLogEvent");
        zzae zzaeVar9 = new zzae();
        zzaeVar9.a(5);
        f12238j = a10.b(zzaeVar9.b()).a();
        FieldDescriptor.Builder a11 = FieldDescriptor.a("onDeviceFaceLoadLogEvent");
        zzae zzaeVar10 = new zzae();
        zzaeVar10.a(59);
        f12239k = a11.b(zzaeVar10.b()).a();
        FieldDescriptor.Builder a12 = FieldDescriptor.a("onDeviceTextDetectionLogEvent");
        zzae zzaeVar11 = new zzae();
        zzaeVar11.a(6);
        f12240l = a12.b(zzaeVar11.b()).a();
        FieldDescriptor.Builder a13 = FieldDescriptor.a("onDeviceTextDetectionLoadLogEvent");
        zzae zzaeVar12 = new zzae();
        zzaeVar12.a(79);
        f12241m = a13.b(zzaeVar12.b()).a();
        FieldDescriptor.Builder a14 = FieldDescriptor.a("onDeviceBarcodeDetectionLogEvent");
        zzae zzaeVar13 = new zzae();
        zzaeVar13.a(7);
        f12242n = a14.b(zzaeVar13.b()).a();
        FieldDescriptor.Builder a15 = FieldDescriptor.a("onDeviceBarcodeLoadLogEvent");
        zzae zzaeVar14 = new zzae();
        zzaeVar14.a(58);
        f12243o = a15.b(zzaeVar14.b()).a();
        FieldDescriptor.Builder a16 = FieldDescriptor.a("onDeviceImageLabelCreateLogEvent");
        zzae zzaeVar15 = new zzae();
        zzaeVar15.a(48);
        f12244p = a16.b(zzaeVar15.b()).a();
        FieldDescriptor.Builder a17 = FieldDescriptor.a("onDeviceImageLabelLoadLogEvent");
        zzae zzaeVar16 = new zzae();
        zzaeVar16.a(49);
        f12245q = a17.b(zzaeVar16.b()).a();
        FieldDescriptor.Builder a18 = FieldDescriptor.a("onDeviceImageLabelDetectionLogEvent");
        zzae zzaeVar17 = new zzae();
        zzaeVar17.a(18);
        f12246r = a18.b(zzaeVar17.b()).a();
        FieldDescriptor.Builder a19 = FieldDescriptor.a("onDeviceObjectCreateLogEvent");
        zzae zzaeVar18 = new zzae();
        zzaeVar18.a(26);
        f12247s = a19.b(zzaeVar18.b()).a();
        FieldDescriptor.Builder a20 = FieldDescriptor.a("onDeviceObjectLoadLogEvent");
        zzae zzaeVar19 = new zzae();
        zzaeVar19.a(27);
        t = a20.b(zzaeVar19.b()).a();
        FieldDescriptor.Builder a21 = FieldDescriptor.a("onDeviceObjectInferenceLogEvent");
        zzae zzaeVar20 = new zzae();
        zzaeVar20.a(28);
        u = a21.b(zzaeVar20.b()).a();
        FieldDescriptor.Builder a22 = FieldDescriptor.a("onDevicePoseDetectionLogEvent");
        zzae zzaeVar21 = new zzae();
        zzaeVar21.a(44);
        v = a22.b(zzaeVar21.b()).a();
        FieldDescriptor.Builder a23 = FieldDescriptor.a("onDeviceSegmentationLogEvent");
        zzae zzaeVar22 = new zzae();
        zzaeVar22.a(45);
        w = a23.b(zzaeVar22.b()).a();
        FieldDescriptor.Builder a24 = FieldDescriptor.a("onDeviceSmartReplyLogEvent");
        zzae zzaeVar23 = new zzae();
        zzaeVar23.a(19);
        x = a24.b(zzaeVar23.b()).a();
        FieldDescriptor.Builder a25 = FieldDescriptor.a("onDeviceLanguageIdentificationLogEvent");
        zzae zzaeVar24 = new zzae();
        zzaeVar24.a(21);
        y = a25.b(zzaeVar24.b()).a();
        FieldDescriptor.Builder a26 = FieldDescriptor.a("onDeviceTranslationLogEvent");
        zzae zzaeVar25 = new zzae();
        zzaeVar25.a(22);
        z = a26.b(zzaeVar25.b()).a();
        FieldDescriptor.Builder a27 = FieldDescriptor.a("cloudFaceDetectionLogEvent");
        zzae zzaeVar26 = new zzae();
        zzaeVar26.a(8);
        A = a27.b(zzaeVar26.b()).a();
        FieldDescriptor.Builder a28 = FieldDescriptor.a("cloudCropHintDetectionLogEvent");
        zzae zzaeVar27 = new zzae();
        zzaeVar27.a(9);
        B = a28.b(zzaeVar27.b()).a();
        FieldDescriptor.Builder a29 = FieldDescriptor.a("cloudDocumentTextDetectionLogEvent");
        zzae zzaeVar28 = new zzae();
        zzaeVar28.a(10);
        C = a29.b(zzaeVar28.b()).a();
        FieldDescriptor.Builder a30 = FieldDescriptor.a("cloudImagePropertiesDetectionLogEvent");
        zzae zzaeVar29 = new zzae();
        zzaeVar29.a(11);
        D = a30.b(zzaeVar29.b()).a();
        FieldDescriptor.Builder a31 = FieldDescriptor.a("cloudImageLabelDetectionLogEvent");
        zzae zzaeVar30 = new zzae();
        zzaeVar30.a(12);
        E = a31.b(zzaeVar30.b()).a();
        FieldDescriptor.Builder a32 = FieldDescriptor.a("cloudLandmarkDetectionLogEvent");
        zzae zzaeVar31 = new zzae();
        zzaeVar31.a(13);
        F = a32.b(zzaeVar31.b()).a();
        FieldDescriptor.Builder a33 = FieldDescriptor.a("cloudLogoDetectionLogEvent");
        zzae zzaeVar32 = new zzae();
        zzaeVar32.a(14);
        G = a33.b(zzaeVar32.b()).a();
        FieldDescriptor.Builder a34 = FieldDescriptor.a("cloudSafeSearchDetectionLogEvent");
        zzae zzaeVar33 = new zzae();
        zzaeVar33.a(15);
        H = a34.b(zzaeVar33.b()).a();
        FieldDescriptor.Builder a35 = FieldDescriptor.a("cloudTextDetectionLogEvent");
        zzae zzaeVar34 = new zzae();
        zzaeVar34.a(16);
        I = a35.b(zzaeVar34.b()).a();
        FieldDescriptor.Builder a36 = FieldDescriptor.a("cloudWebSearchDetectionLogEvent");
        zzae zzaeVar35 = new zzae();
        zzaeVar35.a(17);
        J = a36.b(zzaeVar35.b()).a();
        FieldDescriptor.Builder a37 = FieldDescriptor.a("automlImageLabelingCreateLogEvent");
        zzae zzaeVar36 = new zzae();
        zzaeVar36.a(23);
        K = a37.b(zzaeVar36.b()).a();
        FieldDescriptor.Builder a38 = FieldDescriptor.a("automlImageLabelingLoadLogEvent");
        zzae zzaeVar37 = new zzae();
        zzaeVar37.a(24);
        L = a38.b(zzaeVar37.b()).a();
        FieldDescriptor.Builder a39 = FieldDescriptor.a("automlImageLabelingInferenceLogEvent");
        zzae zzaeVar38 = new zzae();
        zzaeVar38.a(25);
        M = a39.b(zzaeVar38.b()).a();
        FieldDescriptor.Builder a40 = FieldDescriptor.a("isModelDownloadedLogEvent");
        zzae zzaeVar39 = new zzae();
        zzaeVar39.a(39);
        N = a40.b(zzaeVar39.b()).a();
        FieldDescriptor.Builder a41 = FieldDescriptor.a("deleteModelLogEvent");
        zzae zzaeVar40 = new zzae();
        zzaeVar40.a(40);
        O = a41.b(zzaeVar40.b()).a();
        FieldDescriptor.Builder a42 = FieldDescriptor.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzae zzaeVar41 = new zzae();
        zzaeVar41.a(30);
        P = a42.b(zzaeVar41.b()).a();
        FieldDescriptor.Builder a43 = FieldDescriptor.a("aggregatedCustomModelInferenceLogEvent");
        zzae zzaeVar42 = new zzae();
        zzaeVar42.a(31);
        Q = a43.b(zzaeVar42.b()).a();
        FieldDescriptor.Builder a44 = FieldDescriptor.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzae zzaeVar43 = new zzae();
        zzaeVar43.a(32);
        R = a44.b(zzaeVar43.b()).a();
        FieldDescriptor.Builder a45 = FieldDescriptor.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzae zzaeVar44 = new zzae();
        zzaeVar44.a(33);
        S = a45.b(zzaeVar44.b()).a();
        FieldDescriptor.Builder a46 = FieldDescriptor.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzae zzaeVar45 = new zzae();
        zzaeVar45.a(34);
        T = a46.b(zzaeVar45.b()).a();
        FieldDescriptor.Builder a47 = FieldDescriptor.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzae zzaeVar46 = new zzae();
        zzaeVar46.a(35);
        U = a47.b(zzaeVar46.b()).a();
        FieldDescriptor.Builder a48 = FieldDescriptor.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzae zzaeVar47 = new zzae();
        zzaeVar47.a(36);
        V = a48.b(zzaeVar47.b()).a();
        FieldDescriptor.Builder a49 = FieldDescriptor.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzae zzaeVar48 = new zzae();
        zzaeVar48.a(46);
        W = a49.b(zzaeVar48.b()).a();
        FieldDescriptor.Builder a50 = FieldDescriptor.a("aggregatedOnDeviceSegmentationLogEvent");
        zzae zzaeVar49 = new zzae();
        zzaeVar49.a(47);
        X = a50.b(zzaeVar49.b()).a();
        FieldDescriptor.Builder a51 = FieldDescriptor.a("pipelineAccelerationInferenceEvents");
        zzae zzaeVar50 = new zzae();
        zzaeVar50.a(69);
        Y = a51.b(zzaeVar50.b()).a();
        FieldDescriptor.Builder a52 = FieldDescriptor.a("remoteConfigLogEvent");
        zzae zzaeVar51 = new zzae();
        zzaeVar51.a(42);
        Z = a52.b(zzaeVar51.b()).a();
        FieldDescriptor.Builder a53 = FieldDescriptor.a("inputImageConstructionLogEvent");
        zzae zzaeVar52 = new zzae();
        zzaeVar52.a(50);
        a0 = a53.b(zzaeVar52.b()).a();
        FieldDescriptor.Builder a54 = FieldDescriptor.a("leakedHandleEvent");
        zzae zzaeVar53 = new zzae();
        zzaeVar53.a(51);
        b0 = a54.b(zzaeVar53.b()).a();
        FieldDescriptor.Builder a55 = FieldDescriptor.a("cameraSourceLogEvent");
        zzae zzaeVar54 = new zzae();
        zzaeVar54.a(52);
        c0 = a55.b(zzaeVar54.b()).a();
        FieldDescriptor.Builder a56 = FieldDescriptor.a("imageLabelOptionalModuleLogEvent");
        zzae zzaeVar55 = new zzae();
        zzaeVar55.a(53);
        d0 = a56.b(zzaeVar55.b()).a();
        FieldDescriptor.Builder a57 = FieldDescriptor.a("languageIdentificationOptionalModuleLogEvent");
        zzae zzaeVar56 = new zzae();
        zzaeVar56.a(54);
        e0 = a57.b(zzaeVar56.b()).a();
        FieldDescriptor.Builder a58 = FieldDescriptor.a("faceDetectionOptionalModuleLogEvent");
        zzae zzaeVar57 = new zzae();
        zzaeVar57.a(60);
        f0 = a58.b(zzaeVar57.b()).a();
        FieldDescriptor.Builder a59 = FieldDescriptor.a("documentDetectionOptionalModuleLogEvent");
        zzae zzaeVar58 = new zzae();
        zzaeVar58.a(85);
        g0 = a59.b(zzaeVar58.b()).a();
        FieldDescriptor.Builder a60 = FieldDescriptor.a("documentCroppingOptionalModuleLogEvent");
        zzae zzaeVar59 = new zzae();
        zzaeVar59.a(86);
        h0 = a60.b(zzaeVar59.b()).a();
        FieldDescriptor.Builder a61 = FieldDescriptor.a("documentEnhancementOptionalModuleLogEvent");
        zzae zzaeVar60 = new zzae();
        zzaeVar60.a(87);
        i0 = a61.b(zzaeVar60.b()).a();
        FieldDescriptor.Builder a62 = FieldDescriptor.a("nlClassifierOptionalModuleLogEvent");
        zzae zzaeVar61 = new zzae();
        zzaeVar61.a(55);
        j0 = a62.b(zzaeVar61.b()).a();
        FieldDescriptor.Builder a63 = FieldDescriptor.a("nlClassifierClientLibraryLogEvent");
        zzae zzaeVar62 = new zzae();
        zzaeVar62.a(56);
        k0 = a63.b(zzaeVar62.b()).a();
        FieldDescriptor.Builder a64 = FieldDescriptor.a("accelerationAllowlistLogEvent");
        zzae zzaeVar63 = new zzae();
        zzaeVar63.a(57);
        l0 = a64.b(zzaeVar63.b()).a();
        FieldDescriptor.Builder a65 = FieldDescriptor.a("toxicityDetectionCreateEvent");
        zzae zzaeVar64 = new zzae();
        zzaeVar64.a(62);
        m0 = a65.b(zzaeVar64.b()).a();
        FieldDescriptor.Builder a66 = FieldDescriptor.a("toxicityDetectionLoadEvent");
        zzae zzaeVar65 = new zzae();
        zzaeVar65.a(63);
        n0 = a66.b(zzaeVar65.b()).a();
        FieldDescriptor.Builder a67 = FieldDescriptor.a("toxicityDetectionInferenceEvent");
        zzae zzaeVar66 = new zzae();
        zzaeVar66.a(64);
        o0 = a67.b(zzaeVar66.b()).a();
        FieldDescriptor.Builder a68 = FieldDescriptor.a("barcodeDetectionOptionalModuleLogEvent");
        zzae zzaeVar67 = new zzae();
        zzaeVar67.a(65);
        p0 = a68.b(zzaeVar67.b()).a();
        FieldDescriptor.Builder a69 = FieldDescriptor.a("customImageLabelOptionalModuleLogEvent");
        zzae zzaeVar68 = new zzae();
        zzaeVar68.a(66);
        q0 = a69.b(zzaeVar68.b()).a();
        FieldDescriptor.Builder a70 = FieldDescriptor.a("codeScannerScanApiEvent");
        zzae zzaeVar69 = new zzae();
        zzaeVar69.a(67);
        r0 = a70.b(zzaeVar69.b()).a();
        FieldDescriptor.Builder a71 = FieldDescriptor.a("codeScannerOptionalModuleEvent");
        zzae zzaeVar70 = new zzae();
        zzaeVar70.a(68);
        s0 = a71.b(zzaeVar70.b()).a();
        FieldDescriptor.Builder a72 = FieldDescriptor.a("onDeviceExplicitContentCreateLogEvent");
        zzae zzaeVar71 = new zzae();
        zzaeVar71.a(70);
        t0 = a72.b(zzaeVar71.b()).a();
        FieldDescriptor.Builder a73 = FieldDescriptor.a("onDeviceExplicitContentLoadLogEvent");
        zzae zzaeVar72 = new zzae();
        zzaeVar72.a(71);
        u0 = a73.b(zzaeVar72.b()).a();
        FieldDescriptor.Builder a74 = FieldDescriptor.a("onDeviceExplicitContentInferenceLogEvent");
        zzae zzaeVar73 = new zzae();
        zzaeVar73.a(72);
        v0 = a74.b(zzaeVar73.b()).a();
        FieldDescriptor.Builder a75 = FieldDescriptor.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzae zzaeVar74 = new zzae();
        zzaeVar74.a(73);
        w0 = a75.b(zzaeVar74.b()).a();
        FieldDescriptor.Builder a76 = FieldDescriptor.a("onDeviceFaceMeshCreateLogEvent");
        zzae zzaeVar75 = new zzae();
        zzaeVar75.a(74);
        x0 = a76.b(zzaeVar75.b()).a();
        FieldDescriptor.Builder a77 = FieldDescriptor.a("onDeviceFaceMeshLoadLogEvent");
        zzae zzaeVar76 = new zzae();
        zzaeVar76.a(75);
        y0 = a77.b(zzaeVar76.b()).a();
        FieldDescriptor.Builder a78 = FieldDescriptor.a("onDeviceFaceMeshLogEvent");
        zzae zzaeVar77 = new zzae();
        zzaeVar77.a(76);
        z0 = a78.b(zzaeVar77.b()).a();
        FieldDescriptor.Builder a79 = FieldDescriptor.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzae zzaeVar78 = new zzae();
        zzaeVar78.a(77);
        A0 = a79.b(zzaeVar78.b()).a();
        FieldDescriptor.Builder a80 = FieldDescriptor.a("smartReplyOptionalModuleLogEvent");
        zzae zzaeVar79 = new zzae();
        zzaeVar79.a(78);
        B0 = a80.b(zzaeVar79.b()).a();
        FieldDescriptor.Builder a81 = FieldDescriptor.a("textDetectionOptionalModuleLogEvent");
        zzae zzaeVar80 = new zzae();
        zzaeVar80.a(80);
        C0 = a81.b(zzaeVar80.b()).a();
        FieldDescriptor.Builder a82 = FieldDescriptor.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzae zzaeVar81 = new zzae();
        zzaeVar81.a(81);
        D0 = a82.b(zzaeVar81.b()).a();
        FieldDescriptor.Builder a83 = FieldDescriptor.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzae zzaeVar82 = new zzae();
        zzaeVar82.a(82);
        E0 = a83.b(zzaeVar82.b()).a();
        FieldDescriptor.Builder a84 = FieldDescriptor.a("onDeviceImageQualityAnalysisLogEvent");
        zzae zzaeVar83 = new zzae();
        zzaeVar83.a(83);
        F0 = a84.b(zzaeVar83.b()).a();
        FieldDescriptor.Builder a85 = FieldDescriptor.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzae zzaeVar84 = new zzae();
        zzaeVar84.a(84);
        G0 = a85.b(zzaeVar84.b()).a();
        FieldDescriptor.Builder a86 = FieldDescriptor.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzae zzaeVar85 = new zzae();
        zzaeVar85.a(88);
        H0 = a86.b(zzaeVar85.b()).a();
        FieldDescriptor.Builder a87 = FieldDescriptor.a("imageCaptioningOptionalModuleLogEvent");
        zzae zzaeVar86 = new zzae();
        zzaeVar86.a(89);
        I0 = a87.b(zzaeVar86.b()).a();
        FieldDescriptor.Builder a88 = FieldDescriptor.a("onDeviceImageCaptioningCreateLogEvent");
        zzae zzaeVar87 = new zzae();
        zzaeVar87.a(90);
        J0 = a88.b(zzaeVar87.b()).a();
        FieldDescriptor.Builder a89 = FieldDescriptor.a("onDeviceImageCaptioningLoadLogEvent");
        zzae zzaeVar88 = new zzae();
        zzaeVar88.a(91);
        K0 = a89.b(zzaeVar88.b()).a();
        FieldDescriptor.Builder a90 = FieldDescriptor.a("onDeviceImageCaptioningInferenceLogEvent");
        zzae zzaeVar89 = new zzae();
        zzaeVar89.a(92);
        L0 = a90.b(zzaeVar89.b()).a();
        FieldDescriptor.Builder a91 = FieldDescriptor.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzae zzaeVar90 = new zzae();
        zzaeVar90.a(93);
        M0 = a91.b(zzaeVar90.b()).a();
    }

    private zzeo() {
    }

    @Override // com.google.firebase.encoders.ObjectEncoder
    public final /* bridge */ /* synthetic */ void a(Object obj, Object obj2) {
        zziy zziyVar = (zziy) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.c(f12230b, zziyVar.c());
        objectEncoderContext.c(f12231c, zziyVar.b());
        objectEncoderContext.c(f12232d, null);
        objectEncoderContext.c(f12233e, null);
        objectEncoderContext.c(f12234f, null);
        objectEncoderContext.c(f12235g, null);
        objectEncoderContext.c(f12236h, null);
        objectEncoderContext.c(f12237i, null);
        objectEncoderContext.c(f12238j, null);
        objectEncoderContext.c(f12239k, null);
        objectEncoderContext.c(f12240l, null);
        objectEncoderContext.c(f12241m, null);
        objectEncoderContext.c(f12242n, null);
        objectEncoderContext.c(f12243o, null);
        objectEncoderContext.c(f12244p, null);
        objectEncoderContext.c(f12245q, null);
        objectEncoderContext.c(f12246r, null);
        objectEncoderContext.c(f12247s, null);
        objectEncoderContext.c(t, null);
        objectEncoderContext.c(u, null);
        objectEncoderContext.c(v, null);
        objectEncoderContext.c(w, null);
        objectEncoderContext.c(x, null);
        objectEncoderContext.c(y, null);
        objectEncoderContext.c(z, null);
        objectEncoderContext.c(A, null);
        objectEncoderContext.c(B, null);
        objectEncoderContext.c(C, null);
        objectEncoderContext.c(D, null);
        objectEncoderContext.c(E, null);
        objectEncoderContext.c(F, null);
        objectEncoderContext.c(G, null);
        objectEncoderContext.c(H, null);
        objectEncoderContext.c(I, null);
        objectEncoderContext.c(J, null);
        objectEncoderContext.c(K, null);
        objectEncoderContext.c(L, null);
        objectEncoderContext.c(M, null);
        objectEncoderContext.c(N, null);
        objectEncoderContext.c(O, null);
        objectEncoderContext.c(P, null);
        objectEncoderContext.c(Q, null);
        objectEncoderContext.c(R, null);
        objectEncoderContext.c(S, null);
        objectEncoderContext.c(T, null);
        objectEncoderContext.c(U, null);
        objectEncoderContext.c(V, null);
        objectEncoderContext.c(W, null);
        objectEncoderContext.c(X, null);
        objectEncoderContext.c(Y, null);
        objectEncoderContext.c(Z, null);
        objectEncoderContext.c(a0, zziyVar.a());
        objectEncoderContext.c(b0, null);
        objectEncoderContext.c(c0, null);
        objectEncoderContext.c(d0, null);
        objectEncoderContext.c(e0, null);
        objectEncoderContext.c(f0, null);
        objectEncoderContext.c(g0, null);
        objectEncoderContext.c(h0, null);
        objectEncoderContext.c(i0, null);
        objectEncoderContext.c(j0, null);
        objectEncoderContext.c(k0, null);
        objectEncoderContext.c(l0, null);
        objectEncoderContext.c(m0, null);
        objectEncoderContext.c(n0, null);
        objectEncoderContext.c(o0, null);
        objectEncoderContext.c(p0, null);
        objectEncoderContext.c(q0, null);
        objectEncoderContext.c(r0, null);
        objectEncoderContext.c(s0, null);
        objectEncoderContext.c(t0, null);
        objectEncoderContext.c(u0, null);
        objectEncoderContext.c(v0, null);
        objectEncoderContext.c(w0, null);
        objectEncoderContext.c(x0, null);
        objectEncoderContext.c(y0, null);
        objectEncoderContext.c(z0, null);
        objectEncoderContext.c(A0, null);
        objectEncoderContext.c(B0, null);
        objectEncoderContext.c(C0, null);
        objectEncoderContext.c(D0, null);
        objectEncoderContext.c(E0, null);
        objectEncoderContext.c(F0, null);
        objectEncoderContext.c(G0, null);
        objectEncoderContext.c(H0, null);
        objectEncoderContext.c(I0, null);
        objectEncoderContext.c(J0, null);
        objectEncoderContext.c(K0, null);
        objectEncoderContext.c(L0, null);
        objectEncoderContext.c(M0, null);
    }
}
