package com.google.android.gms.internal.mlkit_vision_text_common;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import com.zte.distbus.basetransfer.Status;

/* loaded from: classes.dex */
final class zzio implements ObjectEncoder {
    private static final FieldDescriptor A;
    private static final FieldDescriptor A0;
    private static final FieldDescriptor B;
    private static final FieldDescriptor B0;
    private static final FieldDescriptor C;
    private static final FieldDescriptor C0;
    private static final FieldDescriptor D;
    private static final FieldDescriptor D0;
    private static final FieldDescriptor E;
    private static final FieldDescriptor E0;
    private static final FieldDescriptor F;
    private static final FieldDescriptor F0;
    private static final FieldDescriptor G;
    private static final FieldDescriptor G0;
    private static final FieldDescriptor H;
    private static final FieldDescriptor H0;
    private static final FieldDescriptor I;
    private static final FieldDescriptor I0;
    private static final FieldDescriptor J;
    private static final FieldDescriptor J0;
    private static final FieldDescriptor K;
    private static final FieldDescriptor K0;
    private static final FieldDescriptor L;
    private static final FieldDescriptor L0;
    private static final FieldDescriptor M;
    private static final FieldDescriptor M0;
    private static final FieldDescriptor N;
    private static final FieldDescriptor N0;
    private static final FieldDescriptor O;
    private static final FieldDescriptor O0;
    private static final FieldDescriptor P;
    private static final FieldDescriptor P0;
    private static final FieldDescriptor Q;
    private static final FieldDescriptor Q0;
    private static final FieldDescriptor R;
    private static final FieldDescriptor R0;
    private static final FieldDescriptor S;
    private static final FieldDescriptor S0;
    private static final FieldDescriptor T;
    private static final FieldDescriptor T0;
    private static final FieldDescriptor U;
    private static final FieldDescriptor U0;
    private static final FieldDescriptor V;
    private static final FieldDescriptor V0;
    private static final FieldDescriptor W;
    private static final FieldDescriptor W0;
    private static final FieldDescriptor X;
    private static final FieldDescriptor X0;
    private static final FieldDescriptor Y;
    private static final FieldDescriptor Y0;
    private static final FieldDescriptor Z;
    private static final FieldDescriptor Z0;

    /* renamed from: a, reason: collision with root package name */
    static final zzio f13306a = new zzio();
    private static final FieldDescriptor a0;
    private static final FieldDescriptor a1;

    /* renamed from: b, reason: collision with root package name */
    private static final FieldDescriptor f13307b;
    private static final FieldDescriptor b0;
    private static final FieldDescriptor b1;

    /* renamed from: c, reason: collision with root package name */
    private static final FieldDescriptor f13308c;
    private static final FieldDescriptor c0;
    private static final FieldDescriptor c1;

    /* renamed from: d, reason: collision with root package name */
    private static final FieldDescriptor f13309d;
    private static final FieldDescriptor d0;
    private static final FieldDescriptor d1;

    /* renamed from: e, reason: collision with root package name */
    private static final FieldDescriptor f13310e;
    private static final FieldDescriptor e0;
    private static final FieldDescriptor e1;

    /* renamed from: f, reason: collision with root package name */
    private static final FieldDescriptor f13311f;
    private static final FieldDescriptor f0;
    private static final FieldDescriptor f1;

    /* renamed from: g, reason: collision with root package name */
    private static final FieldDescriptor f13312g;
    private static final FieldDescriptor g0;
    private static final FieldDescriptor g1;

    /* renamed from: h, reason: collision with root package name */
    private static final FieldDescriptor f13313h;
    private static final FieldDescriptor h0;
    private static final FieldDescriptor h1;

    /* renamed from: i, reason: collision with root package name */
    private static final FieldDescriptor f13314i;
    private static final FieldDescriptor i0;
    private static final FieldDescriptor i1;

    /* renamed from: j, reason: collision with root package name */
    private static final FieldDescriptor f13315j;
    private static final FieldDescriptor j0;
    private static final FieldDescriptor j1;

    /* renamed from: k, reason: collision with root package name */
    private static final FieldDescriptor f13316k;
    private static final FieldDescriptor k0;
    private static final FieldDescriptor k1;

    /* renamed from: l, reason: collision with root package name */
    private static final FieldDescriptor f13317l;
    private static final FieldDescriptor l0;
    private static final FieldDescriptor l1;

    /* renamed from: m, reason: collision with root package name */
    private static final FieldDescriptor f13318m;
    private static final FieldDescriptor m0;
    private static final FieldDescriptor m1;

    /* renamed from: n, reason: collision with root package name */
    private static final FieldDescriptor f13319n;
    private static final FieldDescriptor n0;
    private static final FieldDescriptor n1;

    /* renamed from: o, reason: collision with root package name */
    private static final FieldDescriptor f13320o;
    private static final FieldDescriptor o0;
    private static final FieldDescriptor o1;

    /* renamed from: p, reason: collision with root package name */
    private static final FieldDescriptor f13321p;
    private static final FieldDescriptor p0;
    private static final FieldDescriptor p1;

    /* renamed from: q, reason: collision with root package name */
    private static final FieldDescriptor f13322q;
    private static final FieldDescriptor q0;
    private static final FieldDescriptor q1;

    /* renamed from: r, reason: collision with root package name */
    private static final FieldDescriptor f13323r;
    private static final FieldDescriptor r0;
    private static final FieldDescriptor r1;

    /* renamed from: s, reason: collision with root package name */
    private static final FieldDescriptor f13324s;
    private static final FieldDescriptor s0;
    private static final FieldDescriptor s1;
    private static final FieldDescriptor t;
    private static final FieldDescriptor t0;
    private static final FieldDescriptor t1;
    private static final FieldDescriptor u;
    private static final FieldDescriptor u0;
    private static final FieldDescriptor u1;
    private static final FieldDescriptor v;
    private static final FieldDescriptor v0;
    private static final FieldDescriptor v1;
    private static final FieldDescriptor w;
    private static final FieldDescriptor w0;
    private static final FieldDescriptor w1;
    private static final FieldDescriptor x;
    private static final FieldDescriptor x0;
    private static final FieldDescriptor x1;
    private static final FieldDescriptor y;
    private static final FieldDescriptor y0;
    private static final FieldDescriptor y1;
    private static final FieldDescriptor z;
    private static final FieldDescriptor z0;

    static {
        FieldDescriptor.Builder a2 = FieldDescriptor.a("systemInfo");
        zzct zzctVar = new zzct();
        zzctVar.a(1);
        f13307b = a2.b(zzctVar.b()).a();
        FieldDescriptor.Builder a3 = FieldDescriptor.a("eventName");
        zzct zzctVar2 = new zzct();
        zzctVar2.a(2);
        f13308c = a3.b(zzctVar2.b()).a();
        FieldDescriptor.Builder a4 = FieldDescriptor.a("isThickClient");
        zzct zzctVar3 = new zzct();
        zzctVar3.a(37);
        f13309d = a4.b(zzctVar3.b()).a();
        FieldDescriptor.Builder a5 = FieldDescriptor.a("clientType");
        zzct zzctVar4 = new zzct();
        zzctVar4.a(61);
        f13310e = a5.b(zzctVar4.b()).a();
        FieldDescriptor.Builder a6 = FieldDescriptor.a("modelDownloadLogEvent");
        zzct zzctVar5 = new zzct();
        zzctVar5.a(3);
        f13311f = a6.b(zzctVar5.b()).a();
        FieldDescriptor.Builder a7 = FieldDescriptor.a("customModelLoadLogEvent");
        zzct zzctVar6 = new zzct();
        zzctVar6.a(20);
        f13312g = a7.b(zzctVar6.b()).a();
        FieldDescriptor.Builder a8 = FieldDescriptor.a("customModelInferenceLogEvent");
        zzct zzctVar7 = new zzct();
        zzctVar7.a(4);
        f13313h = a8.b(zzctVar7.b()).a();
        FieldDescriptor.Builder a9 = FieldDescriptor.a("customModelCreateLogEvent");
        zzct zzctVar8 = new zzct();
        zzctVar8.a(29);
        f13314i = a9.b(zzctVar8.b()).a();
        FieldDescriptor.Builder a10 = FieldDescriptor.a("onDeviceFaceDetectionLogEvent");
        zzct zzctVar9 = new zzct();
        zzctVar9.a(5);
        f13315j = a10.b(zzctVar9.b()).a();
        FieldDescriptor.Builder a11 = FieldDescriptor.a("onDeviceFaceLoadLogEvent");
        zzct zzctVar10 = new zzct();
        zzctVar10.a(59);
        f13316k = a11.b(zzctVar10.b()).a();
        FieldDescriptor.Builder a12 = FieldDescriptor.a("onDeviceTextDetectionLogEvent");
        zzct zzctVar11 = new zzct();
        zzctVar11.a(6);
        f13317l = a12.b(zzctVar11.b()).a();
        FieldDescriptor.Builder a13 = FieldDescriptor.a("onDeviceTextDetectionLoadLogEvent");
        zzct zzctVar12 = new zzct();
        zzctVar12.a(79);
        f13318m = a13.b(zzctVar12.b()).a();
        FieldDescriptor.Builder a14 = FieldDescriptor.a("onDeviceBarcodeDetectionLogEvent");
        zzct zzctVar13 = new zzct();
        zzctVar13.a(7);
        f13319n = a14.b(zzctVar13.b()).a();
        FieldDescriptor.Builder a15 = FieldDescriptor.a("onDeviceBarcodeLoadLogEvent");
        zzct zzctVar14 = new zzct();
        zzctVar14.a(58);
        f13320o = a15.b(zzctVar14.b()).a();
        FieldDescriptor.Builder a16 = FieldDescriptor.a("onDeviceImageLabelCreateLogEvent");
        zzct zzctVar15 = new zzct();
        zzctVar15.a(48);
        f13321p = a16.b(zzctVar15.b()).a();
        FieldDescriptor.Builder a17 = FieldDescriptor.a("onDeviceImageLabelLoadLogEvent");
        zzct zzctVar16 = new zzct();
        zzctVar16.a(49);
        f13322q = a17.b(zzctVar16.b()).a();
        FieldDescriptor.Builder a18 = FieldDescriptor.a("onDeviceImageLabelDetectionLogEvent");
        zzct zzctVar17 = new zzct();
        zzctVar17.a(18);
        f13323r = a18.b(zzctVar17.b()).a();
        FieldDescriptor.Builder a19 = FieldDescriptor.a("onDeviceObjectCreateLogEvent");
        zzct zzctVar18 = new zzct();
        zzctVar18.a(26);
        f13324s = a19.b(zzctVar18.b()).a();
        FieldDescriptor.Builder a20 = FieldDescriptor.a("onDeviceObjectLoadLogEvent");
        zzct zzctVar19 = new zzct();
        zzctVar19.a(27);
        t = a20.b(zzctVar19.b()).a();
        FieldDescriptor.Builder a21 = FieldDescriptor.a("onDeviceObjectInferenceLogEvent");
        zzct zzctVar20 = new zzct();
        zzctVar20.a(28);
        u = a21.b(zzctVar20.b()).a();
        FieldDescriptor.Builder a22 = FieldDescriptor.a("onDevicePoseDetectionLogEvent");
        zzct zzctVar21 = new zzct();
        zzctVar21.a(44);
        v = a22.b(zzctVar21.b()).a();
        FieldDescriptor.Builder a23 = FieldDescriptor.a("onDeviceSegmentationLogEvent");
        zzct zzctVar22 = new zzct();
        zzctVar22.a(45);
        w = a23.b(zzctVar22.b()).a();
        FieldDescriptor.Builder a24 = FieldDescriptor.a("onDeviceSmartReplyLogEvent");
        zzct zzctVar23 = new zzct();
        zzctVar23.a(19);
        x = a24.b(zzctVar23.b()).a();
        FieldDescriptor.Builder a25 = FieldDescriptor.a("onDeviceLanguageIdentificationLogEvent");
        zzct zzctVar24 = new zzct();
        zzctVar24.a(21);
        y = a25.b(zzctVar24.b()).a();
        FieldDescriptor.Builder a26 = FieldDescriptor.a("onDeviceTranslationLogEvent");
        zzct zzctVar25 = new zzct();
        zzctVar25.a(22);
        z = a26.b(zzctVar25.b()).a();
        FieldDescriptor.Builder a27 = FieldDescriptor.a("cloudFaceDetectionLogEvent");
        zzct zzctVar26 = new zzct();
        zzctVar26.a(8);
        A = a27.b(zzctVar26.b()).a();
        FieldDescriptor.Builder a28 = FieldDescriptor.a("cloudCropHintDetectionLogEvent");
        zzct zzctVar27 = new zzct();
        zzctVar27.a(9);
        B = a28.b(zzctVar27.b()).a();
        FieldDescriptor.Builder a29 = FieldDescriptor.a("cloudDocumentTextDetectionLogEvent");
        zzct zzctVar28 = new zzct();
        zzctVar28.a(10);
        C = a29.b(zzctVar28.b()).a();
        FieldDescriptor.Builder a30 = FieldDescriptor.a("cloudImagePropertiesDetectionLogEvent");
        zzct zzctVar29 = new zzct();
        zzctVar29.a(11);
        D = a30.b(zzctVar29.b()).a();
        FieldDescriptor.Builder a31 = FieldDescriptor.a("cloudImageLabelDetectionLogEvent");
        zzct zzctVar30 = new zzct();
        zzctVar30.a(12);
        E = a31.b(zzctVar30.b()).a();
        FieldDescriptor.Builder a32 = FieldDescriptor.a("cloudLandmarkDetectionLogEvent");
        zzct zzctVar31 = new zzct();
        zzctVar31.a(13);
        F = a32.b(zzctVar31.b()).a();
        FieldDescriptor.Builder a33 = FieldDescriptor.a("cloudLogoDetectionLogEvent");
        zzct zzctVar32 = new zzct();
        zzctVar32.a(14);
        G = a33.b(zzctVar32.b()).a();
        FieldDescriptor.Builder a34 = FieldDescriptor.a("cloudSafeSearchDetectionLogEvent");
        zzct zzctVar33 = new zzct();
        zzctVar33.a(15);
        H = a34.b(zzctVar33.b()).a();
        FieldDescriptor.Builder a35 = FieldDescriptor.a("cloudTextDetectionLogEvent");
        zzct zzctVar34 = new zzct();
        zzctVar34.a(16);
        I = a35.b(zzctVar34.b()).a();
        FieldDescriptor.Builder a36 = FieldDescriptor.a("cloudWebSearchDetectionLogEvent");
        zzct zzctVar35 = new zzct();
        zzctVar35.a(17);
        J = a36.b(zzctVar35.b()).a();
        FieldDescriptor.Builder a37 = FieldDescriptor.a("automlImageLabelingCreateLogEvent");
        zzct zzctVar36 = new zzct();
        zzctVar36.a(23);
        K = a37.b(zzctVar36.b()).a();
        FieldDescriptor.Builder a38 = FieldDescriptor.a("automlImageLabelingLoadLogEvent");
        zzct zzctVar37 = new zzct();
        zzctVar37.a(24);
        L = a38.b(zzctVar37.b()).a();
        FieldDescriptor.Builder a39 = FieldDescriptor.a("automlImageLabelingInferenceLogEvent");
        zzct zzctVar38 = new zzct();
        zzctVar38.a(25);
        M = a39.b(zzctVar38.b()).a();
        FieldDescriptor.Builder a40 = FieldDescriptor.a("isModelDownloadedLogEvent");
        zzct zzctVar39 = new zzct();
        zzctVar39.a(39);
        N = a40.b(zzctVar39.b()).a();
        FieldDescriptor.Builder a41 = FieldDescriptor.a("deleteModelLogEvent");
        zzct zzctVar40 = new zzct();
        zzctVar40.a(40);
        O = a41.b(zzctVar40.b()).a();
        FieldDescriptor.Builder a42 = FieldDescriptor.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzct zzctVar41 = new zzct();
        zzctVar41.a(30);
        P = a42.b(zzctVar41.b()).a();
        FieldDescriptor.Builder a43 = FieldDescriptor.a("aggregatedCustomModelInferenceLogEvent");
        zzct zzctVar42 = new zzct();
        zzctVar42.a(31);
        Q = a43.b(zzctVar42.b()).a();
        FieldDescriptor.Builder a44 = FieldDescriptor.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzct zzctVar43 = new zzct();
        zzctVar43.a(32);
        R = a44.b(zzctVar43.b()).a();
        FieldDescriptor.Builder a45 = FieldDescriptor.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzct zzctVar44 = new zzct();
        zzctVar44.a(33);
        S = a45.b(zzctVar44.b()).a();
        FieldDescriptor.Builder a46 = FieldDescriptor.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzct zzctVar45 = new zzct();
        zzctVar45.a(34);
        T = a46.b(zzctVar45.b()).a();
        FieldDescriptor.Builder a47 = FieldDescriptor.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzct zzctVar46 = new zzct();
        zzctVar46.a(35);
        U = a47.b(zzctVar46.b()).a();
        FieldDescriptor.Builder a48 = FieldDescriptor.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzct zzctVar47 = new zzct();
        zzctVar47.a(36);
        V = a48.b(zzctVar47.b()).a();
        FieldDescriptor.Builder a49 = FieldDescriptor.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzct zzctVar48 = new zzct();
        zzctVar48.a(46);
        W = a49.b(zzctVar48.b()).a();
        FieldDescriptor.Builder a50 = FieldDescriptor.a("aggregatedOnDeviceSegmentationLogEvent");
        zzct zzctVar49 = new zzct();
        zzctVar49.a(47);
        X = a50.b(zzctVar49.b()).a();
        FieldDescriptor.Builder a51 = FieldDescriptor.a("pipelineAccelerationInferenceEvents");
        zzct zzctVar50 = new zzct();
        zzctVar50.a(69);
        Y = a51.b(zzctVar50.b()).a();
        FieldDescriptor.Builder a52 = FieldDescriptor.a("remoteConfigLogEvent");
        zzct zzctVar51 = new zzct();
        zzctVar51.a(42);
        Z = a52.b(zzctVar51.b()).a();
        FieldDescriptor.Builder a53 = FieldDescriptor.a("inputImageConstructionLogEvent");
        zzct zzctVar52 = new zzct();
        zzctVar52.a(50);
        a0 = a53.b(zzctVar52.b()).a();
        FieldDescriptor.Builder a54 = FieldDescriptor.a("leakedHandleEvent");
        zzct zzctVar53 = new zzct();
        zzctVar53.a(51);
        b0 = a54.b(zzctVar53.b()).a();
        FieldDescriptor.Builder a55 = FieldDescriptor.a("cameraSourceLogEvent");
        zzct zzctVar54 = new zzct();
        zzctVar54.a(52);
        c0 = a55.b(zzctVar54.b()).a();
        FieldDescriptor.Builder a56 = FieldDescriptor.a("imageLabelOptionalModuleLogEvent");
        zzct zzctVar55 = new zzct();
        zzctVar55.a(53);
        d0 = a56.b(zzctVar55.b()).a();
        FieldDescriptor.Builder a57 = FieldDescriptor.a("languageIdentificationOptionalModuleLogEvent");
        zzct zzctVar56 = new zzct();
        zzctVar56.a(54);
        e0 = a57.b(zzctVar56.b()).a();
        FieldDescriptor.Builder a58 = FieldDescriptor.a("faceDetectionOptionalModuleLogEvent");
        zzct zzctVar57 = new zzct();
        zzctVar57.a(60);
        f0 = a58.b(zzctVar57.b()).a();
        FieldDescriptor.Builder a59 = FieldDescriptor.a("documentDetectionOptionalModuleLogEvent");
        zzct zzctVar58 = new zzct();
        zzctVar58.a(85);
        g0 = a59.b(zzctVar58.b()).a();
        FieldDescriptor.Builder a60 = FieldDescriptor.a("documentCroppingOptionalModuleLogEvent");
        zzct zzctVar59 = new zzct();
        zzctVar59.a(86);
        h0 = a60.b(zzctVar59.b()).a();
        FieldDescriptor.Builder a61 = FieldDescriptor.a("documentEnhancementOptionalModuleLogEvent");
        zzct zzctVar60 = new zzct();
        zzctVar60.a(87);
        i0 = a61.b(zzctVar60.b()).a();
        FieldDescriptor.Builder a62 = FieldDescriptor.a("nlClassifierOptionalModuleLogEvent");
        zzct zzctVar61 = new zzct();
        zzctVar61.a(55);
        j0 = a62.b(zzctVar61.b()).a();
        FieldDescriptor.Builder a63 = FieldDescriptor.a("nlClassifierClientLibraryLogEvent");
        zzct zzctVar62 = new zzct();
        zzctVar62.a(56);
        k0 = a63.b(zzctVar62.b()).a();
        FieldDescriptor.Builder a64 = FieldDescriptor.a("accelerationAllowlistLogEvent");
        zzct zzctVar63 = new zzct();
        zzctVar63.a(57);
        l0 = a64.b(zzctVar63.b()).a();
        FieldDescriptor.Builder a65 = FieldDescriptor.a("toxicityDetectionCreateEvent");
        zzct zzctVar64 = new zzct();
        zzctVar64.a(62);
        m0 = a65.b(zzctVar64.b()).a();
        FieldDescriptor.Builder a66 = FieldDescriptor.a("toxicityDetectionLoadEvent");
        zzct zzctVar65 = new zzct();
        zzctVar65.a(63);
        n0 = a66.b(zzctVar65.b()).a();
        FieldDescriptor.Builder a67 = FieldDescriptor.a("toxicityDetectionInferenceEvent");
        zzct zzctVar66 = new zzct();
        zzctVar66.a(64);
        o0 = a67.b(zzctVar66.b()).a();
        FieldDescriptor.Builder a68 = FieldDescriptor.a("barcodeDetectionOptionalModuleLogEvent");
        zzct zzctVar67 = new zzct();
        zzctVar67.a(65);
        p0 = a68.b(zzctVar67.b()).a();
        FieldDescriptor.Builder a69 = FieldDescriptor.a("customImageLabelOptionalModuleLogEvent");
        zzct zzctVar68 = new zzct();
        zzctVar68.a(66);
        q0 = a69.b(zzctVar68.b()).a();
        FieldDescriptor.Builder a70 = FieldDescriptor.a("codeScannerScanApiEvent");
        zzct zzctVar69 = new zzct();
        zzctVar69.a(67);
        r0 = a70.b(zzctVar69.b()).a();
        FieldDescriptor.Builder a71 = FieldDescriptor.a("codeScannerOptionalModuleEvent");
        zzct zzctVar70 = new zzct();
        zzctVar70.a(68);
        s0 = a71.b(zzctVar70.b()).a();
        FieldDescriptor.Builder a72 = FieldDescriptor.a("onDeviceExplicitContentCreateLogEvent");
        zzct zzctVar71 = new zzct();
        zzctVar71.a(70);
        t0 = a72.b(zzctVar71.b()).a();
        FieldDescriptor.Builder a73 = FieldDescriptor.a("onDeviceExplicitContentLoadLogEvent");
        zzct zzctVar72 = new zzct();
        zzctVar72.a(71);
        u0 = a73.b(zzctVar72.b()).a();
        FieldDescriptor.Builder a74 = FieldDescriptor.a("onDeviceExplicitContentInferenceLogEvent");
        zzct zzctVar73 = new zzct();
        zzctVar73.a(72);
        v0 = a74.b(zzctVar73.b()).a();
        FieldDescriptor.Builder a75 = FieldDescriptor.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzct zzctVar74 = new zzct();
        zzctVar74.a(73);
        w0 = a75.b(zzctVar74.b()).a();
        FieldDescriptor.Builder a76 = FieldDescriptor.a("onDeviceFaceMeshCreateLogEvent");
        zzct zzctVar75 = new zzct();
        zzctVar75.a(74);
        x0 = a76.b(zzctVar75.b()).a();
        FieldDescriptor.Builder a77 = FieldDescriptor.a("onDeviceFaceMeshLoadLogEvent");
        zzct zzctVar76 = new zzct();
        zzctVar76.a(75);
        y0 = a77.b(zzctVar76.b()).a();
        FieldDescriptor.Builder a78 = FieldDescriptor.a("onDeviceFaceMeshLogEvent");
        zzct zzctVar77 = new zzct();
        zzctVar77.a(76);
        z0 = a78.b(zzctVar77.b()).a();
        FieldDescriptor.Builder a79 = FieldDescriptor.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzct zzctVar78 = new zzct();
        zzctVar78.a(77);
        A0 = a79.b(zzctVar78.b()).a();
        FieldDescriptor.Builder a80 = FieldDescriptor.a("smartReplyOptionalModuleLogEvent");
        zzct zzctVar79 = new zzct();
        zzctVar79.a(78);
        B0 = a80.b(zzctVar79.b()).a();
        FieldDescriptor.Builder a81 = FieldDescriptor.a("textDetectionOptionalModuleLogEvent");
        zzct zzctVar80 = new zzct();
        zzctVar80.a(80);
        C0 = a81.b(zzctVar80.b()).a();
        FieldDescriptor.Builder a82 = FieldDescriptor.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzct zzctVar81 = new zzct();
        zzctVar81.a(81);
        D0 = a82.b(zzctVar81.b()).a();
        FieldDescriptor.Builder a83 = FieldDescriptor.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzct zzctVar82 = new zzct();
        zzctVar82.a(82);
        E0 = a83.b(zzctVar82.b()).a();
        FieldDescriptor.Builder a84 = FieldDescriptor.a("onDeviceImageQualityAnalysisLogEvent");
        zzct zzctVar83 = new zzct();
        zzctVar83.a(83);
        F0 = a84.b(zzctVar83.b()).a();
        FieldDescriptor.Builder a85 = FieldDescriptor.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzct zzctVar84 = new zzct();
        zzctVar84.a(84);
        G0 = a85.b(zzctVar84.b()).a();
        FieldDescriptor.Builder a86 = FieldDescriptor.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzct zzctVar85 = new zzct();
        zzctVar85.a(88);
        H0 = a86.b(zzctVar85.b()).a();
        FieldDescriptor.Builder a87 = FieldDescriptor.a("imageCaptioningOptionalModuleLogEvent");
        zzct zzctVar86 = new zzct();
        zzctVar86.a(89);
        I0 = a87.b(zzctVar86.b()).a();
        FieldDescriptor.Builder a88 = FieldDescriptor.a("onDeviceImageCaptioningCreateLogEvent");
        zzct zzctVar87 = new zzct();
        zzctVar87.a(90);
        J0 = a88.b(zzctVar87.b()).a();
        FieldDescriptor.Builder a89 = FieldDescriptor.a("onDeviceImageCaptioningLoadLogEvent");
        zzct zzctVar88 = new zzct();
        zzctVar88.a(91);
        K0 = a89.b(zzctVar88.b()).a();
        FieldDescriptor.Builder a90 = FieldDescriptor.a("onDeviceImageCaptioningInferenceLogEvent");
        zzct zzctVar89 = new zzct();
        zzctVar89.a(92);
        L0 = a90.b(zzctVar89.b()).a();
        FieldDescriptor.Builder a91 = FieldDescriptor.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzct zzctVar90 = new zzct();
        zzctVar90.a(93);
        M0 = a91.b(zzctVar90.b()).a();
        FieldDescriptor.Builder a92 = FieldDescriptor.a("onDeviceDocumentDetectionCreateLogEvent");
        zzct zzctVar91 = new zzct();
        zzctVar91.a(94);
        N0 = a92.b(zzctVar91.b()).a();
        FieldDescriptor.Builder a93 = FieldDescriptor.a("onDeviceDocumentDetectionLoadLogEvent");
        zzct zzctVar92 = new zzct();
        zzctVar92.a(95);
        O0 = a93.b(zzctVar92.b()).a();
        FieldDescriptor.Builder a94 = FieldDescriptor.a("onDeviceDocumentDetectionLogEvent");
        zzct zzctVar93 = new zzct();
        zzctVar93.a(96);
        P0 = a94.b(zzctVar93.b()).a();
        FieldDescriptor.Builder a95 = FieldDescriptor.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzct zzctVar94 = new zzct();
        zzctVar94.a(97);
        Q0 = a95.b(zzctVar94.b()).a();
        FieldDescriptor.Builder a96 = FieldDescriptor.a("onDeviceDocumentCroppingCreateLogEvent");
        zzct zzctVar95 = new zzct();
        zzctVar95.a(98);
        R0 = a96.b(zzctVar95.b()).a();
        FieldDescriptor.Builder a97 = FieldDescriptor.a("onDeviceDocumentCroppingLoadLogEvent");
        zzct zzctVar96 = new zzct();
        zzctVar96.a(99);
        S0 = a97.b(zzctVar96.b()).a();
        FieldDescriptor.Builder a98 = FieldDescriptor.a("onDeviceDocumentCroppingLogEvent");
        zzct zzctVar97 = new zzct();
        zzctVar97.a(100);
        T0 = a98.b(zzctVar97.b()).a();
        FieldDescriptor.Builder a99 = FieldDescriptor.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzct zzctVar98 = new zzct();
        zzctVar98.a(101);
        U0 = a99.b(zzctVar98.b()).a();
        FieldDescriptor.Builder a100 = FieldDescriptor.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzct zzctVar99 = new zzct();
        zzctVar99.a(102);
        V0 = a100.b(zzctVar99.b()).a();
        FieldDescriptor.Builder a101 = FieldDescriptor.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzct zzctVar100 = new zzct();
        zzctVar100.a(Status.BLE_DISCONNECTING);
        W0 = a101.b(zzctVar100.b()).a();
        FieldDescriptor.Builder a102 = FieldDescriptor.a("onDeviceDocumentEnhancementLogEvent");
        zzct zzctVar101 = new zzct();
        zzctVar101.a(Status.BLE_ERROR);
        X0 = a102.b(zzctVar101.b()).a();
        FieldDescriptor.Builder a103 = FieldDescriptor.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzct zzctVar102 = new zzct();
        zzctVar102.a(105);
        Y0 = a103.b(zzctVar102.b()).a();
        FieldDescriptor.Builder a104 = FieldDescriptor.a("scannerAutoZoomEvent");
        zzct zzctVar103 = new zzct();
        zzctVar103.a(106);
        Z0 = a104.b(zzctVar103.b()).a();
        FieldDescriptor.Builder a105 = FieldDescriptor.a("lowLightAutoExposureComputationEvent");
        zzct zzctVar104 = new zzct();
        zzctVar104.a(107);
        a1 = a105.b(zzctVar104.b()).a();
        FieldDescriptor.Builder a106 = FieldDescriptor.a("lowLightFrameProcessEvent");
        zzct zzctVar105 = new zzct();
        zzctVar105.a(108);
        b1 = a106.b(zzctVar105.b()).a();
        FieldDescriptor.Builder a107 = FieldDescriptor.a("lowLightSceneDetectionEvent");
        zzct zzctVar106 = new zzct();
        zzctVar106.a(109);
        c1 = a107.b(zzctVar106.b()).a();
        FieldDescriptor.Builder a108 = FieldDescriptor.a("onDeviceStainRemovalLogEvent");
        zzct zzctVar107 = new zzct();
        zzctVar107.a(110);
        d1 = a108.b(zzctVar107.b()).a();
        FieldDescriptor.Builder a109 = FieldDescriptor.a("aggregatedOnDeviceStainRemovalLogEvent");
        zzct zzctVar108 = new zzct();
        zzctVar108.a(111);
        e1 = a109.b(zzctVar108.b()).a();
        FieldDescriptor.Builder a110 = FieldDescriptor.a("stainRemovalOptionalModuleLogEvent");
        zzct zzctVar109 = new zzct();
        zzctVar109.a(112);
        f1 = a110.b(zzctVar109.b()).a();
        FieldDescriptor.Builder a111 = FieldDescriptor.a("onDeviceShadowRemovalLogEvent");
        zzct zzctVar110 = new zzct();
        zzctVar110.a(113);
        g1 = a111.b(zzctVar110.b()).a();
        FieldDescriptor.Builder a112 = FieldDescriptor.a("aggregatedOnDeviceShadowRemovalLogEvent");
        zzct zzctVar111 = new zzct();
        zzctVar111.a(114);
        h1 = a112.b(zzctVar111.b()).a();
        FieldDescriptor.Builder a113 = FieldDescriptor.a("shadowRemovalOptionalModuleLogEvent");
        zzct zzctVar112 = new zzct();
        zzctVar112.a(115);
        i1 = a113.b(zzctVar112.b()).a();
        FieldDescriptor.Builder a114 = FieldDescriptor.a("onDeviceDigitalInkSegmentationLogEvent");
        zzct zzctVar113 = new zzct();
        zzctVar113.a(116);
        j1 = a114.b(zzctVar113.b()).a();
        FieldDescriptor.Builder a115 = FieldDescriptor.a("onDeviceDocumentScannerStartLogEvent");
        zzct zzctVar114 = new zzct();
        zzctVar114.a(117);
        k1 = a115.b(zzctVar114.b()).a();
        FieldDescriptor.Builder a116 = FieldDescriptor.a("onDeviceDocumentScannerFinishLogEvent");
        zzct zzctVar115 = new zzct();
        zzctVar115.a(118);
        l1 = a116.b(zzctVar115.b()).a();
        FieldDescriptor.Builder a117 = FieldDescriptor.a("onDeviceDocumentScannerUiStartLogEvent");
        zzct zzctVar116 = new zzct();
        zzctVar116.a(119);
        m1 = a117.b(zzctVar116.b()).a();
        FieldDescriptor.Builder a118 = FieldDescriptor.a("onDeviceDocumentScannerUiFinishLogEvent");
        zzct zzctVar117 = new zzct();
        zzctVar117.a(120);
        n1 = a118.b(zzctVar117.b()).a();
        FieldDescriptor.Builder a119 = FieldDescriptor.a("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzct zzctVar118 = new zzct();
        zzctVar118.a(121);
        o1 = a119.b(zzctVar118.b()).a();
        FieldDescriptor.Builder a120 = FieldDescriptor.a("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzct zzctVar119 = new zzct();
        zzctVar119.a(122);
        p1 = a120.b(zzctVar119.b()).a();
        FieldDescriptor.Builder a121 = FieldDescriptor.a("onDeviceDocumentScannerUiCreateLogEvent");
        zzct zzctVar120 = new zzct();
        zzctVar120.a(123);
        q1 = a121.b(zzctVar120.b()).a();
        FieldDescriptor.Builder a122 = FieldDescriptor.a("onDeviceSubjectSegmentationCreateLogEvent");
        zzct zzctVar121 = new zzct();
        zzctVar121.a(124);
        r1 = a122.b(zzctVar121.b()).a();
        FieldDescriptor.Builder a123 = FieldDescriptor.a("onDeviceSubjectSegmentationLoadLogEvent");
        zzct zzctVar122 = new zzct();
        zzctVar122.a(125);
        s1 = a123.b(zzctVar122.b()).a();
        FieldDescriptor.Builder a124 = FieldDescriptor.a("onDeviceSubjectSegmentationInferenceLogEvent");
        zzct zzctVar123 = new zzct();
        zzctVar123.a(126);
        t1 = a124.b(zzctVar123.b()).a();
        FieldDescriptor.Builder a125 = FieldDescriptor.a("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzct zzctVar124 = new zzct();
        zzctVar124.a(127);
        u1 = a125.b(zzctVar124.b()).a();
        FieldDescriptor.Builder a126 = FieldDescriptor.a("subjectSegmentationOptionalModuleLogEvent");
        zzct zzctVar125 = new zzct();
        zzctVar125.a(128);
        v1 = a126.b(zzctVar125.b()).a();
        FieldDescriptor.Builder a127 = FieldDescriptor.a("documentScannerUiModuleScreenViewEvent");
        zzct zzctVar126 = new zzct();
        zzctVar126.a(129);
        w1 = a127.b(zzctVar126.b()).a();
        FieldDescriptor.Builder a128 = FieldDescriptor.a("documentScannerUiModuleScreenClickEvent");
        zzct zzctVar127 = new zzct();
        zzctVar127.a(130);
        x1 = a128.b(zzctVar127.b()).a();
        FieldDescriptor.Builder a129 = FieldDescriptor.a("documentScannerUiModuleScreenErrorEvent");
        zzct zzctVar128 = new zzct();
        zzctVar128.a(131);
        y1 = a129.b(zzctVar128.b()).a();
    }

    private zzio() {
    }

    @Override // com.google.firebase.encoders.ObjectEncoder
    public final /* bridge */ /* synthetic */ void a(Object obj, Object obj2) {
        zzoy zzoyVar = (zzoy) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.c(f13307b, zzoyVar.f());
        objectEncoderContext.c(f13308c, zzoyVar.c());
        objectEncoderContext.c(f13309d, null);
        objectEncoderContext.c(f13310e, zzoyVar.b());
        objectEncoderContext.c(f13311f, null);
        objectEncoderContext.c(f13312g, null);
        objectEncoderContext.c(f13313h, null);
        objectEncoderContext.c(f13314i, null);
        objectEncoderContext.c(f13315j, null);
        objectEncoderContext.c(f13316k, null);
        objectEncoderContext.c(f13317l, zzoyVar.e());
        objectEncoderContext.c(f13318m, zzoyVar.d());
        objectEncoderContext.c(f13319n, null);
        objectEncoderContext.c(f13320o, null);
        objectEncoderContext.c(f13321p, null);
        objectEncoderContext.c(f13322q, null);
        objectEncoderContext.c(f13323r, null);
        objectEncoderContext.c(f13324s, null);
        objectEncoderContext.c(t, null);
        objectEncoderContext.c(u, null);
        objectEncoderContext.c(v, null);
        objectEncoderContext.c(w, null);
        objectEncoderContext.c(x, null);
        objectEncoderContext.c(y, null);
        objectEncoderContext.c(z, null);
        objectEncoderContext.c(A, null);
        objectEncoderContext.c(B, null);
        objectEncoderContext.c(C, null);
        objectEncoderContext.c(D, null);
        objectEncoderContext.c(E, null);
        objectEncoderContext.c(F, null);
        objectEncoderContext.c(G, null);
        objectEncoderContext.c(H, null);
        objectEncoderContext.c(I, null);
        objectEncoderContext.c(J, null);
        objectEncoderContext.c(K, null);
        objectEncoderContext.c(L, null);
        objectEncoderContext.c(M, null);
        objectEncoderContext.c(N, null);
        objectEncoderContext.c(O, null);
        objectEncoderContext.c(P, null);
        objectEncoderContext.c(Q, null);
        objectEncoderContext.c(R, null);
        objectEncoderContext.c(S, null);
        objectEncoderContext.c(T, null);
        objectEncoderContext.c(U, null);
        objectEncoderContext.c(V, zzoyVar.a());
        objectEncoderContext.c(W, null);
        objectEncoderContext.c(X, null);
        objectEncoderContext.c(Y, null);
        objectEncoderContext.c(Z, null);
        objectEncoderContext.c(a0, null);
        objectEncoderContext.c(b0, null);
        objectEncoderContext.c(c0, null);
        objectEncoderContext.c(d0, null);
        objectEncoderContext.c(e0, null);
        objectEncoderContext.c(f0, null);
        objectEncoderContext.c(g0, null);
        objectEncoderContext.c(h0, null);
        objectEncoderContext.c(i0, null);
        objectEncoderContext.c(j0, null);
        objectEncoderContext.c(k0, null);
        objectEncoderContext.c(l0, null);
        objectEncoderContext.c(m0, null);
        objectEncoderContext.c(n0, null);
        objectEncoderContext.c(o0, null);
        objectEncoderContext.c(p0, null);
        objectEncoderContext.c(q0, null);
        objectEncoderContext.c(r0, null);
        objectEncoderContext.c(s0, null);
        objectEncoderContext.c(t0, null);
        objectEncoderContext.c(u0, null);
        objectEncoderContext.c(v0, null);
        objectEncoderContext.c(w0, null);
        objectEncoderContext.c(x0, null);
        objectEncoderContext.c(y0, null);
        objectEncoderContext.c(z0, null);
        objectEncoderContext.c(A0, null);
        objectEncoderContext.c(B0, null);
        objectEncoderContext.c(C0, null);
        objectEncoderContext.c(D0, null);
        objectEncoderContext.c(E0, null);
        objectEncoderContext.c(F0, null);
        objectEncoderContext.c(G0, null);
        objectEncoderContext.c(H0, null);
        objectEncoderContext.c(I0, null);
        objectEncoderContext.c(J0, null);
        objectEncoderContext.c(K0, null);
        objectEncoderContext.c(L0, null);
        objectEncoderContext.c(M0, null);
        objectEncoderContext.c(N0, null);
        objectEncoderContext.c(O0, null);
        objectEncoderContext.c(P0, null);
        objectEncoderContext.c(Q0, null);
        objectEncoderContext.c(R0, null);
        objectEncoderContext.c(S0, null);
        objectEncoderContext.c(T0, null);
        objectEncoderContext.c(U0, null);
        objectEncoderContext.c(V0, null);
        objectEncoderContext.c(W0, null);
        objectEncoderContext.c(X0, null);
        objectEncoderContext.c(Y0, null);
        objectEncoderContext.c(Z0, null);
        objectEncoderContext.c(a1, null);
        objectEncoderContext.c(b1, null);
        objectEncoderContext.c(c1, null);
        objectEncoderContext.c(d1, null);
        objectEncoderContext.c(e1, null);
        objectEncoderContext.c(f1, null);
        objectEncoderContext.c(g1, null);
        objectEncoderContext.c(h1, null);
        objectEncoderContext.c(i1, null);
        objectEncoderContext.c(j1, null);
        objectEncoderContext.c(k1, null);
        objectEncoderContext.c(l1, null);
        objectEncoderContext.c(m1, null);
        objectEncoderContext.c(n1, null);
        objectEncoderContext.c(o1, null);
        objectEncoderContext.c(p1, null);
        objectEncoderContext.c(q1, null);
        objectEncoderContext.c(r1, null);
        objectEncoderContext.c(s1, null);
        objectEncoderContext.c(t1, null);
        objectEncoderContext.c(u1, null);
        objectEncoderContext.c(v1, null);
        objectEncoderContext.c(w1, null);
        objectEncoderContext.c(x1, null);
        objectEncoderContext.c(y1, null);
    }
}
