package com.zte.gameassist.lowsugar.utils;

import cn.nubia.gameassist.view.NubiaTextClock;
import java.util.HashMap;
import java.util.Map;

/* loaded from: classes2.dex */
public class OcrTextSimilarityUtil {

    /* renamed from: a, reason: collision with root package name */
    private static final Map f17025a;

    public static class SimilarityResult {

        /* renamed from: a, reason: collision with root package name */
        private final boolean f17026a;

        /* renamed from: b, reason: collision with root package name */
        private final float f17027b;

        public String toString() {
            return "SimilarityResult{isSameSource=" + this.f17026a + ", similarityValue=" + this.f17027b + '}';
        }
    }

    static {
        HashMap hashMap = new HashMap();
        f17025a = hashMap;
        hashMap.put('0', '0');
        hashMap.put('o', '0');
        hashMap.put('O', '0');
        hashMap.put('1', '1');
        hashMap.put('l', '1');
        hashMap.put('I', '1');
        hashMap.put('8', '8');
        hashMap.put('b', '8');
        hashMap.put('B', '8');
        hashMap.put('5', '5');
        Character valueOf = Character.valueOf(NubiaTextClock.SECONDS);
        hashMap.put(valueOf, '5');
        hashMap.put('S', '5');
        hashMap.put('6', '6');
        hashMap.put('G', '6');
        hashMap.put('g', '6');
        hashMap.put('2', '2');
        hashMap.put('Z', '2');
        hashMap.put('z', '2');
        hashMap.put((char) 65292, ',');
        hashMap.put((char) 12290, '.');
        hashMap.put((char) 12289, ',');
        hashMap.put((char) 65509, (char) 165);
        hashMap.put((char) 65284, '$');
        hashMap.put((char) 65285, '%');
        hashMap.put((char) 65293, '-');
        hashMap.put('_', '-');
        hashMap.put((char) 8212, '-');
        hashMap.put((char) 12540, '-');
        hashMap.put((char) 12539, '.');
        hashMap.put((char) 1040, 'A');
        hashMap.put((char) 1072, 'a');
        hashMap.put((char) 1042, 'B');
        hashMap.put((char) 1074, 'b');
        hashMap.put((char) 1045, 'E');
        hashMap.put((char) 1077, 'e');
        hashMap.put((char) 1050, 'K');
        hashMap.put((char) 1082, 'k');
        hashMap.put((char) 1052, 'M');
        hashMap.put((char) 1084, 'm');
        hashMap.put((char) 1053, 'H');
        hashMap.put((char) 1085, 'h');
        hashMap.put((char) 1054, 'O');
        hashMap.put((char) 1086, 'o');
        hashMap.put((char) 1056, 'P');
        hashMap.put((char) 1088, 'p');
        hashMap.put((char) 1057, 'C');
        hashMap.put((char) 1089, 'c');
        hashMap.put((char) 1058, 'T');
        hashMap.put((char) 1090, 't');
        hashMap.put((char) 1059, 'Y');
        hashMap.put((char) 1091, 'y');
        hashMap.put((char) 1061, 'X');
        hashMap.put((char) 1093, 'x');
        hashMap.put((char) 1048, 'I');
        hashMap.put((char) 1080, 'i');
        hashMap.put((char) 1030, 'I');
        hashMap.put((char) 1110, 'i');
        hashMap.put((char) 1028, 'E');
        hashMap.put((char) 1108, 'e');
        hashMap.put((char) 228, 'a');
        hashMap.put((char) 196, 'A');
        hashMap.put((char) 246, 'o');
        hashMap.put((char) 214, 'O');
        hashMap.put((char) 252, 'u');
        hashMap.put((char) 220, 'U');
        hashMap.put((char) 223, valueOf);
        hashMap.put((char) 225, 'a');
        hashMap.put((char) 193, 'A');
        hashMap.put((char) 233, 'e');
        hashMap.put((char) 201, 'E');
        hashMap.put((char) 237, 'i');
        hashMap.put((char) 205, 'I');
        hashMap.put((char) 243, 'o');
        hashMap.put((char) 211, 'O');
        hashMap.put((char) 250, 'u');
        hashMap.put((char) 218, 'U');
        hashMap.put((char) 241, 'n');
        hashMap.put((char) 209, 'N');
        hashMap.put((char) 224, 'a');
        hashMap.put((char) 192, 'A');
        hashMap.put((char) 226, 'a');
        hashMap.put((char) 194, 'A');
        hashMap.put((char) 230, 'a');
        hashMap.put((char) 198, 'A');
        hashMap.put((char) 231, 'c');
        hashMap.put((char) 199, 'C');
        hashMap.put((char) 232, 'e');
        hashMap.put((char) 200, 'E');
        hashMap.put((char) 234, 'e');
        hashMap.put((char) 202, 'E');
        hashMap.put((char) 235, 'e');
        hashMap.put((char) 203, 'E');
        hashMap.put((char) 238, 'i');
        hashMap.put((char) 206, 'I');
        hashMap.put((char) 239, 'i');
        hashMap.put((char) 207, 'I');
        hashMap.put((char) 244, 'o');
        hashMap.put((char) 212, 'O');
        hashMap.put((char) 339, 'o');
        hashMap.put((char) 338, 'O');
        hashMap.put((char) 249, 'u');
        hashMap.put((char) 217, 'U');
        hashMap.put((char) 251, 'u');
        hashMap.put((char) 219, 'U');
        hashMap.put((char) 252, 'u');
        hashMap.put((char) 220, 'U');
        hashMap.put((char) 255, 'y');
        hashMap.put((char) 376, 'Y');
        hashMap.put((char) 224, 'a');
        hashMap.put((char) 192, 'A');
        hashMap.put((char) 232, 'e');
        hashMap.put((char) 200, 'E');
        hashMap.put((char) 233, 'e');
        hashMap.put((char) 201, 'E');
        hashMap.put((char) 236, 'i');
        hashMap.put((char) 204, 'I');
        hashMap.put((char) 242, 'o');
        hashMap.put((char) 210, 'O');
        hashMap.put((char) 249, 'u');
        hashMap.put((char) 217, 'U');
        hashMap.put((char) 261, 'a');
        hashMap.put((char) 260, 'A');
        hashMap.put((char) 263, 'c');
        hashMap.put((char) 262, 'C');
        hashMap.put((char) 281, 'e');
        hashMap.put((char) 280, 'E');
        hashMap.put((char) 322, 'l');
        hashMap.put((char) 321, 'L');
        hashMap.put((char) 324, 'n');
        hashMap.put((char) 323, 'N');
        hashMap.put((char) 243, 'o');
        hashMap.put((char) 211, 'O');
        hashMap.put((char) 347, valueOf);
        hashMap.put((char) 346, 'S');
        hashMap.put((char) 378, 'z');
        hashMap.put((char) 377, 'Z');
        hashMap.put((char) 380, 'z');
        hashMap.put((char) 379, 'Z');
        hashMap.put((char) 225, 'a');
        hashMap.put((char) 193, 'A');
        hashMap.put((char) 224, 'a');
        hashMap.put((char) 192, 'A');
        hashMap.put((char) 226, 'a');
        hashMap.put((char) 194, 'A');
        hashMap.put((char) 227, 'a');
        hashMap.put((char) 195, 'A');
        hashMap.put((char) 233, 'e');
        hashMap.put((char) 201, 'E');
        hashMap.put((char) 234, 'e');
        hashMap.put((char) 202, 'E');
        hashMap.put((char) 237, 'i');
        hashMap.put((char) 205, 'I');
        hashMap.put((char) 243, 'o');
        hashMap.put((char) 211, 'O');
        hashMap.put((char) 244, 'o');
        hashMap.put((char) 212, 'O');
        hashMap.put((char) 245, 'o');
        hashMap.put((char) 213, 'O');
        hashMap.put((char) 250, 'u');
        hashMap.put((char) 218, 'U');
        hashMap.put((char) 231, 'c');
        hashMap.put((char) 199, 'C');
        hashMap.put((char) 259, 'a');
        hashMap.put((char) 258, 'A');
        hashMap.put((char) 226, 'a');
        hashMap.put((char) 194, 'A');
        hashMap.put((char) 238, 'i');
        hashMap.put((char) 206, 'I');
        hashMap.put((char) 537, valueOf);
        hashMap.put((char) 536, 'S');
        hashMap.put((char) 539, 't');
        hashMap.put((char) 538, 'T');
        hashMap.put((char) 225, 'a');
        hashMap.put((char) 193, 'A');
        hashMap.put((char) 269, 'c');
        hashMap.put((char) 268, 'C');
        hashMap.put((char) 271, 'd');
        hashMap.put((char) 270, 'D');
        hashMap.put((char) 233, 'e');
        hashMap.put((char) 201, 'E');
        hashMap.put((char) 283, 'e');
        hashMap.put((char) 282, 'E');
        hashMap.put((char) 237, 'i');
        hashMap.put((char) 205, 'I');
        hashMap.put((char) 328, 'n');
        hashMap.put((char) 327, 'N');
        hashMap.put((char) 243, 'o');
        hashMap.put((char) 211, 'O');
        hashMap.put((char) 345, 'r');
        hashMap.put((char) 344, 'R');
        hashMap.put((char) 353, valueOf);
        hashMap.put((char) 352, 'S');
        hashMap.put((char) 357, 't');
        hashMap.put((char) 356, 'T');
        hashMap.put((char) 250, 'u');
        hashMap.put((char) 218, 'U');
        hashMap.put((char) 367, 'u');
        hashMap.put((char) 366, 'U');
        hashMap.put((char) 253, 'y');
        hashMap.put((char) 221, 'Y');
        hashMap.put((char) 382, 'z');
        hashMap.put((char) 381, 'Z');
        hashMap.put((char) 231, 'c');
        hashMap.put((char) 199, 'C');
        hashMap.put((char) 287, 'g');
        hashMap.put((char) 286, 'G');
        hashMap.put((char) 305, 'i');
        hashMap.put((char) 246, 'o');
        hashMap.put((char) 214, 'O');
        hashMap.put((char) 351, valueOf);
        hashMap.put((char) 350, 'S');
        hashMap.put((char) 252, 'u');
        hashMap.put((char) 220, 'U');
        hashMap.put((char) 263, 'c');
        hashMap.put((char) 262, 'C');
        hashMap.put((char) 269, 'c');
        hashMap.put((char) 268, 'C');
        hashMap.put((char) 273, 'd');
        hashMap.put((char) 272, 'D');
        hashMap.put((char) 353, valueOf);
        hashMap.put((char) 352, 'S');
        hashMap.put((char) 382, 'z');
        hashMap.put((char) 381, 'Z');
    }
}
