package cn.nubia.multisubscreen;

/* loaded from: classes.dex */
public enum CastStatus {
    STATUS_DEFAULT,
    STATUS_BLE_CONNECTING,
    STATUS_BLE_CONNECTED,
    STATUS_LOGIC_CONNECTING,
    STATUS_LOGIC_CONNECTED,
    STATUS_CASTING,
    STATUS_LOGIC_DISCONNECTING,
    STATUS_LOGIC_DISCONNECTED,
    STATUS_BLE_CONNECT_FAIL,
    STATUS_LOGIC_CONNECT_FAIL,
    STATUS_CONNECT_FAIL_SHOW_RETRY
}
